#!/bin/sh

export PATH=/sbin:/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin

echo "Starting Envoy..."
nohup /usr/bin/consul connect envoy -envoy-binary /usr/bin/envoy -sidecar-for mysql > /envoy.out &

echo "Reloading Consul..."
/usr/bin/consul reload

sleep 10

exit 0
