#!/bin/bash

#creds
vault login -method=userpass username=admin password=admin

#check the esm token
vault read consul/creds/esm
if [ $? -ne 0 ]
then
  fail-message "Error checking Consul ESM acl token"
  exit 1
fi

#aws
aws_esm=$(curl -s -H "X-Consul-Token: $(vault kv get -field master_token kv/consul)" "${CONSUL_HTTP_ADDR}/v1/health/service/consul-esm?dc=aws-us-east-1&passing=true")
if [ "$(echo "${aws_esm}" | jq '. | length')" -lt "1" ]; then
  fail-message "AWS ESM is not healthy"
  exit 1
fi

#azure
azure_esm=$(curl -s -H "X-Consul-Token: $(vault kv get -field master_token kv/consul)" "${CONSUL_HTTP_ADDR}/v1/health/service/consul-esm?dc=azure-west-us-2&passing=true")
if [ "$(echo "${azure_esm}" | jq '. | length')" -lt "1" ] ; then
  fail-message "AZURE ESM is not healthy"
  exit 1
fi

#cts
cts_sg=$(aws ec2 describe-security-groups --filter Name="group-id",Values="$(terraform output -state /root/terraform/cache-services/terraform.tfstate elasticache_sg)" | jq '.SecurityGroups[0].IpPermissions[0].IpRanges | length')
if [ "${cts_sg}" != "1" ]; then
  fail-message "CTS did not work. Expecting 1 SG rule."
  exit 1
fi

exit 0
