#!/bin/bash
set -e

sleep 20

# Ensure we load /etc/profile.d/instruqt-env.sh
echo "source /etc/profile.d/instruqt-env.sh" >> /root/.bashrc
source /root/.bashrc

curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -

#wait at least five minutes for Azure User to propagate
az upgrade -y
az account clear
echo "Logging in with Azure SPN..."
n=0
until [ $n -ge 5 ]; do
  az login \
  --username "${INSTRUQT_AZURE_SUBSCRIPTION_CONSUL_USERNAME}" \
  --password "${INSTRUQT_AZURE_SUBSCRIPTION_CONSUL_PASSWORD}" && break
  n=$[$n+1]
  sleep 60
done
if [ $n -ge 5 ]; then
  exit 1
fi

echo ""
echo ""
echo ">>----------------------------<<"
echo ">> Starting Azure VNETs Setup <<"
echo ">>----------------------------<<"

#install consul
cd /tmp
echo "installing consul..."
curl -O https://releases.hashicorp.com/consul/1.9.4+ent/consul_1.9.4+ent_linux_amd64.zip
unzip *.zip
mv consul /usr/local/bin/consul
rm -f *.zip
cd /root

#install vault
cd /tmp
echo "installing vault..."
curl -O https://releases.hashicorp.com/vault/1.4.3/vault_1.4.3_linux_amd64.zip
unzip *.zip
mv vault /usr/local/bin/vault
rm -f *.zip
cd /root

#install terraform
cd /tmp
echo "installing terraform..."
curl -O https://releases.hashicorp.com/terraform/0.13.2/terraform_0.13.2_linux_amd64.zip
unzip *.zip
mv terraform /usr/local/bin/terraform
rm -f *.zip
cd /root

#get assets
echo "cloning assets..."
# //FIXME git clone https://github.com/hashicorp/field-workshops-consul.git
# // Use this dev branch
git clone -b n8-hcs2ent https://github.com/hashicorp/field-workshops-consul.git
cp -r field-workshops-consul/instruqt-tracks/network-infrastructure-automation/assets/terraform /root/terraform
rm -rf field-workshops-consul

#ssh agent
cat << EOF > ~/.ssh/config
Host *
    StrictHostKeyChecking no
EOF
eval $(ssh-agent)
ssh-add ~/.ssh/id_rsa

#fix path
echo "export PATH=/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" >> ~/.bashrc

# Ensure we load /etc/profile.d/instruqt-env.sh
echo "source /etc/profile.d/instruqt-env.sh" >> /root/.bashrc
source /root/.bashrc

# Azure needs time before the next step
sleep 60

#seeing if this fixes the internittent 'subscription not recognized error'
az account set --subscription "${INSTRUQT_AZURE_SUBSCRIPTION_CONSUL_SUBSCRIPTION_ID}"

#enable marketplace
az provider register --namespace 'Microsoft.Solutions' --subscription "${INSTRUQT_AZURE_SUBSCRIPTION_CONSUL_SUBSCRIPTION_ID}"

# Workround for az cli certificate pinning issue: https://github.com/Azure/azure-cli/issues/16858
/opt/az/bin/python3 -m pip install --upgrade pip

#enable hcs ext
az extension add --source https://releases.hashicorp.com/hcs/0.4.4/hcs-0.4.4-py2.py3-none-any.whl --yes

#provision
cd /root/terraform/vnet
/usr/local/bin/terraform init

pubkey=$(cat ~/.ssh/id_rsa.pub)
cat << EOF > /root/terraform/vnet/terraform.tfvars
ssh_public_key = "$(cat ~/.ssh/id_rsa.pub)"
EOF

#assignment
set-workdir /root/terraform/vnet
cd /root/terraform/vnet

echo ""
echo ""
echo ">>----------------------------<<"
echo ">> Azure VNETs Setup Complete <<"
echo ">>----------------------------<<"


exit 0
