#!/bin/bash

echo ""
echo ""
echo ">>-----------------------<<"
echo ">> Deploying Azure VNETs <<"
echo ">>-----------------------<<"

cd /root/terraform/vnet
terraform apply -auto-approve > /root/terraform/vnet/terraform.out

echo ""
echo ""
echo ">>----------------------<<"
echo ">> Azure VNETs Deployed <<"
echo ">>----------------------<<"

exit 0
