#!/bin/bash

export CONSUL_HTTP_TOKEN=$(/usr/local/bin/terraform output -state /root/terraform/consul/terraform.tfstate consul_master_token)
consul_lb=$(/usr/local/bin/terraform output -state /root/terraform/consul/terraform.tfstate consul_lb)
export CONSUL_HTTP_ADDR=http://${consul_lb}

#namespace_sd
/usr/local/bin/consul acl policy read -name cross-namespace-policy
if [ $? -ne 0 ]
then
  fail-message "Error checking cross namespace policy"
  exit 1
fi

#namespaces
/usr/local/bin/consul namespace read frontend
if [ $? -ne 0 ]
then
  fail-message "Error checking frontend namespace"
  exit 1
fi

/usr/local/bin/consul namespace read api
if [ $? -ne 0 ]
then
  fail-message "Error checking api namespace"
  exit 1
fi

#frontend
/usr/local/bin/consul acl policy read -name frontend-agent
if [ $? -ne 0 ]
then
  fail-message "Error checking frontend agent policy"
  exit 1
fi

#api
/usr/local/bin/consul acl policy read -name api-agent
if [ $? -ne 0 ]
then
  fail-message "Error checking api agent policy"
  exit 1
fi

exit 0
