#!/bin/bash

vault login -method=userpass username=operations password=Password1
export CONSUL_HTTP_TOKEN=$(vault kv get -field=master_token secret/consul)

#namespace_sd
consul acl policy read -name cross-namespace-policy
if [ $? -ne 0 ]
then
  fail-message "Error checking cross namespace policy"
  exit 1
fi

#namespaces
consul namespace read frontend
if [ $? -ne 0 ]
then
  fail-message "Error checking frontend namespace"
  exit 1
fi

consul namespace read backend
if [ $? -ne 0 ]
then
  fail-message "Error checking backend namespace"
  exit 1
fi

#frontend
consul acl policy read -name frontend-agent-policy
if [ $? -ne 0 ]
then
  fail-message "Error checking frontend agent policy"
  exit 1
fi

#backend
consul acl policy read -name backend-agent-policy
if [ $? -ne 0 ]
then
  fail-message "Error checking backend agent policy"
  exit 1
fi

exit 0
