#!/bin/bash

set-workdir /root/policies

#consul policies
mkdir /root/policies

#namespace sd
cat << EOF > /root/policies/cross-namespace.hcl
namespace_prefix "" {
  service_prefix "" {
    policy = "read"
  }
  node_prefix "" {
    policy = "read"
  }
}
EOF

#frontend team
cat << EOF > /root/policies/frontend-namespace.hcl
Name = "frontend"
Description = "namespace for frontend team"
ACLs {
  PolicyDefaults = [
    {
      Name = "cross-namespace-policy"
    }
  ]
  RoleDefaults = []
}
EOF
cat << EOF > /root/policies/frontend-team-agent.hcl
node_prefix "ip-10-2-" {
  policy = "write"
}
service_prefix "" {
  policy = "read"
}
EOF

#api team
cat << EOF > /root/policies/api-namespace.hcl
Name = "api"
Description = "namespace for api team"
ACLs {
  PolicyDefaults = [
    {
      Name = "cross-namespace-policy"
    }
  ]
  RoleDefaults = []
}
EOF
cat << EOF > /root/policies/api-team-agent.hcl
node_prefix "ip-10-3-" {
  policy = "write"
}
service_prefix "" {
  policy = "read"
}
EOF

exit 0
