#!/bin/bash

#creds
vault login -method=userpass username=admin password=admin
export CONSUL_HTTP_TOKEN=$(vault kv get -field master_token kv/consul)

#tf
terraform apply -auto-approve | tee terraform.out
sleep 180

exit 0
