# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

version: "3"
containers:
- name: shell
  image: ubuntu
  shell: /bin/bash
  memory: 2048
aws_accounts:
- name: consul
  managed_policies:
  - arn:aws:iam::aws:policy/AdministratorAccess
  