#!/bin/sh
#
# This is a sample cleanup script. Rename this file to cleanup-$CONTAINER
# (where $container is the name of the container as defined in your config.yml),
# and replace this content with your own script.
#
# This script will be run when you cleanup the challenge.
#
# Remember that the exit code is important. See the documentation
# for more information.
#

echo "This is the cleanup script"

exit 0
