#!/bin/bash
set -e

#creds
sleep 30

#fix path
echo "export PATH=/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" >> ~/.bashrc

#cloud client packages
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
apt update -y
apt install software-properties-common -y
apt update -y
curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
apt update -y
apt install terraform=0.13.2 consul=1.9.4 vault=1.7.1 -y

#make vault run in container
/sbin/setcap cap_ipc_lock= /usr/bin/vault

# Ensure we load /etc/profile.d/instruqt-env.sh
echo "source /etc/profile.d/instruqt-env.sh" >> /root/.bashrc
source /root/.bashrc

#wait at least five minutes for Azure User to propagate
#az upgrade -y
az account clear
echo "Logging in with Azure SPN..."
n=0
until [ $n -ge 5 ]; do
  az login \
  --username "${INSTRUQT_AZURE_SUBSCRIPTION_CONSUL_USERNAME}" \
  --password "${INSTRUQT_AZURE_SUBSCRIPTION_CONSUL_PASSWORD}" && break
  n=$[$n+1]
  sleep 60
done
if [ $n -ge 5 ]; then
  exit 1
fi

#get assets
echo "cloning assets..."
git clone https://github.com/hashicorp/field-workshops-consul.git
cp -r field-workshops-consul/instruqt-tracks/network-infrastructure-automation/assets/terraform /root/terraform
rm -rf field-workshops-consul

#ssh agent
cat << EOF > ~/.ssh/config
Host *
    StrictHostKeyChecking no
EOF
eval $(ssh-agent)
ssh-add ~/.ssh/id_rsa

#seeing if this fixes the internittent 'subscription not recognized error'
az account set --subscription "${INSTRUQT_AZURE_SUBSCRIPTION_CONSUL_SUBSCRIPTION_ID}"

#enable marketplace
az provider register --namespace 'Microsoft.Solutions' --subscription "${INSTRUQT_AZURE_SUBSCRIPTION_CONSUL_SUBSCRIPTION_ID}"

# Workround for az cli certificate pinning issue: https://github.com/Azure/azure-cli/issues/16858
/opt/az/bin/python3 -m pip install --upgrade pip

exit 0
