#!/bin/sh
#
# This is a sample solve script. Rename this file to solve-$CONTAINER
# (where $container is the name of the container as defined in your config.yml),
# and replace this content with your own script.
#
# This script will be run when you solve the challenge.
#
# Remember that the exit code is important. See the documentation
# for more information.
#

echo "This is the solve script"

exit 0
