#!/bin/bash

cd /root/terraform/database-services
terraform init

AZURE_CONSUL_IP=$(terraform output -state /root/terraform/azure-consul-secondary/terraform.tfstate azure_consul_public_ip)
cat << EOF > /root/terraform/database-services/terraform.tfvars
consul_http_addr="http://${AZURE_CONSUL_IP}:8500"
EOF

set-workdir /root/terraform/database-services

exit 0
