#!/bin/bash

vault login -method=userpass username=admin password=admin
export CONSUL_HTTP_TOKEN=$(vault kv get -field master_token kv/consul)

consul intention create -deny '*/*' '*/*'

set-workdir /root/policies/consul

exit 0
