#!/bin/bash

echo "Checking VGW..."
rg=$(terraform output -state /root/terraform/vnet/terraform.tfstate resource_group_name)
status=$(az network vnet-gateway list --resource-group ${rg} | jq -r '.[0].provisioningState')
if [ "${status}" != "Succeeded" ] ; then
  fail-message "VGW is not provisioned. Wait a few moments and try again. Current state is: ${status}"
  exit 1
fi

exit 0
