#!/bin/sh

cat <<-EOF > /root/emojify/resolver.yaml
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceResolver
metadata:
  name: emojify-website
spec:
  defaultSubset: 'v1'
  subsets:
    v1:
      filter: 'v1 in Service.Tags'
      onlyPassing: true
    v2:
      filter: 'v2 in Service.Tags'
      onlyPassing: true
EOF

cat <<-EOF > /root/emojify/splitter.yaml
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceSplitter
metadata:
  name: emojify-website
spec:
  splits:
    - weight: 10
      serviceSubset: 'v1'
    - weight: 90
      serviceSubset: 'v2'
EOF

cat <<-EOF > /root/emojify/router.yaml
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceRouter
metadata:
  name: emojify-website
spec:
  routes:
    - match:
        http:
          queryParam:
            - name: 'x-version'
              exact: '1'
      destination:
        service: 'emojify-website'
        serviceSubset: 'v1'
    - match:
        http:
          queryParam:
            - name: 'x-version'
              exact: '2'
      destination:
        service: 'emojify-website'
        serviceSubset: 'v2'
EOF

exit 0
