#!/bin/sh

cat <<-EOF > /root/emojify/resolver.hcl
kind           = "service-resolver"
name           = "emojify-website"
default_subset = "v1"
subsets = {
  "v1" = {
    filter = "v1 in Service.Tags"
  }
  "v2" = {
    filter = "v2 in Service.Tags"
  }
}
EOF

cat <<-EOF > /root/emojify/splitter.hcl
kind = "service-splitter"
name = "emojify-website"
splits = [
  {
    weight         = 10
    service_subset = "v1"
  },
  {
    weight         = 90
    service_subset = "v2"
  },
]
EOF

cat <<-EOF > /root/emojify/router.hcl
kind = "service-router"
name = "emojify-website"
routes = [
  {
    match {
      http {
        query_param = [
          {
            name  = "x-version"
            exact = "1"
          },
        ]
      }
    }
    destination {
      service        = "emojify-website"
      service_subset = "v1"
    }
  },
  {
    match {
      http {
        query_param = [
          {
            name  = "x-version"
            exact = "2"
          },
        ]
      }
    }
    destination {
      service        = "emojify-website"
      service_subset = "v2"
    }
  }
]
EOF

exit 0
