#!/bin/bash

#get rg
rg=$(terraform output -state /root/terraform/vnet/terraform.tfstate resource_group_name)

#check resources
echo "checking Vault..."
status=$(az vm show -g ${rg} --name vault-vm | jq -r '.provisioningState')
if [ "${status}" != "Creating" ] && [ "${status}" != "Updating" ] && [ "${status}" != "Succeeded" ] ; then
  fail-message "Vault is not provisioning/provisioned. Wait a few moments and try again. Current state is: ${status}"
  exit 1
fi

echo "checking Frontend AKS cluster..."
status=$(az aks show -g ${rg} --name frontend-aks | jq -r '.provisioningState')
if [ "${status}" != "Creating" ] && [ "${status}" != "Updating" ] && [ "${status}" != "Succeeded" ] ; then
  fail-message "Frontend AKS cluster is not provisioning/provisioned. Wait a few moments and try again. Current state is: ${status}"
  exit 1
fi

echo "checking Backend AKS cluster..."
status=$(az aks show -g ${rg} --name backend-aks | jq -r '.provisioningState')
if [ "${status}" != "Creating" ] && [ "${status}" != "Updating" ] && [ "${status}" != "Succeeded" ] ; then
  fail-message "Backend AKS cluster is not provisioning/provisioned. Wait a few moments and try again. Current state is: ${status}"
  exit 1
fi

echo "Checking VGW..."
status=$(az network vnet-gateway list --resource-group ${rg} | jq -r '.[0].provisioningState')
if [ "${status}" != "Creating" ] && [ "${status}" != "Updating" ] && [ "${status}" != "Succeeded" ] ; then
  fail-message "VGW is not provisioning/provisioned. Wait a few moments and try again. Current state is: ${status}"
  exit 1
fi

exit 0
