#!/bin/bash

#cred issue
sleep 120

cd /root/terraform/vault
nohup terraform apply -refresh=false -auto-approve > /root/terraform/vault/terraform.out &
sleep 10

cd /root/terraform/aks
nohup terraform apply -refresh=false -auto-approve > /root/terraform/aks/terraform.out &
sleep 10

cd /root/terraform/vgw
nohup terraform apply -refresh=false -auto-approve > /root/terraform/vgw/terraform.out &
sleep 10

sleep 60

exit 0
