#!/bin/bash

#cd /root/terraform/eks
#terraform  apply -auto-approve

KUBECONFIG=/root/terraform/eks/kubeconfig_frontend:/root/terraform/eks/kubeconfig_backend kubectl config view --merge --flatten > ~/.kube/config

exit 0
