#!/bin/bash

cd /root/terraform/consul-secondaries
terraform init

set-workdir /root/terraform/consul-secondaries

pubkey=$(cat ~/.ssh/id_rsa.pub)
cat << EOF > /root/terraform/consul/terraform.tfvars
gcp_project_id="$(echo $INSTRUQT_GCP_PROJECT_CONSUL_PROJECT_ID)"
ssh_public_key="${pubkey}"
EOF

exit 0
