#!/bin/bash

# azure resources
rg=$(terraform output -state /root/terraform/vnet/terraform.tfstate resource_group_name)
echo "Checking consul-terraform-sync instance"
status=$(az vm get-instance-view -g $rg --name consul-terraform-sync | jq -r .provisioningState)
echo $status

if [ "${status}" != "Creating" ] && [ "${status}" != "Updating" ] && [ "${status}" != "Succeeded" ] ; then
  fail-message "consul-terraform-sync instance is not provisioned. Wait a few moments and try again. Current state is: ${status}"
  exit 1
fi

#check the app works
app=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080)
if [ "${app}" != "200" ]; then
  fail-message "App did not return a 200."
  exit 1
fi

exit 0
