#!/bin/bash

echo ""
echo ">>"
echo ">> Installing Consul Terraform Sync"
echo ">>"

cd /root/terraform/consul-tf-sync
terraform apply -auto-approve > /root/terraform/consul-tf-sync/terraform.out

# Wait until things are actually set up
n=0
while /bin/true; do
    n=$((n+1))
    echo "Try ${n}"
    rg=$(terraform output -state /root/terraform/vnet/terraform.tfstate resource_group_name)
    echo "Checking consul-terraform-sync instance in resource group $rg:"
    status=$(az vm get-instance-view -g $rg --name consul-terraform-sync | jq -r .provisioningState)
    echo $status

    if [ "${status}" != "Creating" ] && [ "${status}" != "Updating" ] && [ "${status}" != "Succeeded" ] ; then
      echo "consul-terraform-sync instance is not provisioned, current state is: ${status}. Sleeping and retrying."
      sleep 20
      continue
    fi

    #check the app works
    app=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080)
    if [ "${app}" != "200" ]; then
      echo "App did not return a 200, returned ${app}. Sleeping and retrying."
      sleep 20
      continue
    fi

    break
done


exit 0
