#!/bin/bash

consul_lb=$(terraform output -state /root/terraform/hcs/terraform.tfstate consul_url)
echo "Consul Load balancer is: $consul_lb"
if [ -z "${consul_lb}" ]; then
  fail-message "Consul is not provisioned yet"
  exit 1
fi

exit 0
