#!/bin/bash

set-workdir /root/terraform/hcs

cd /root/terraform/hcs
terraform init

#import the marketplace agreement if it exists for some reason
terraform import azurerm_marketplace_agreement.hcs "/subscriptions/${INSTRUQT_AZURE_SUBSCRIPTION_CONSUL_SUBSCRIPTION_ID}/providers/Microsoft.MarketplaceOrdering/agreements/hashicorp-4665790/offers/hcs-production/plans/on-demand-v2"

exit 0
