---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: web

---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  type: LoadBalancer
  selector:
    app: web
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 9090

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
      annotations:
        "consul.hashicorp.com/connect-service-upstreams": "api.backend:9091"
    spec:
      serviceAccountName: web
      containers:
      - name: web
        image: "nicholasjackson/fake-service:v0.7.8"
        imagePullPolicy: Always
        ports:
        - containerPort: 9090
        env:
          - name: LISTEN_ADDR
            value: "0.0.0.0:9090"
          - name: UPSTREAM_URIS
            value: "grpc://127.0.0.1:9091"
          - name: MESSAGE
            value: "Hello World"
          - name: NAME
            value: "web"
          - name: SERVER_TYPE
            value: "http"
          - name: TIMING_50_PERCENTILE
            value: "30ms"
          - name: TIMING_90_PERCENTILE
            value: "60ms"
          - name: TIMING_90_PERCENTILE
            value: "90ms"
          - name: TIMING_VARIANCE
            value: "10"
          - name: TRACING_ZIPKIN
            value: "http://jaeger-collector:9411"
