#!/bin/bash

#provison EKS clusters in the background
cd /root/terraform/eks
terraform init
nohup terraform apply -auto-approve > /root/terraform/eks/terraform.out &

#provison Vault in the background
cd /root/terraform/vault
terraform init
nohup terraform apply -auto-approve > /root/terraform/vault/terraform.out &

exit 0
