#!/bin/bash

#path
echo "export PATH=/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" >> ~/.bashrc

set-workdir /root/terraform/vpc

sleep 10
aws configure set default.region us-east-1
aws ec2 create-default-vpc

#ssh
aws ec2 import-key-pair --key-name "instruqt" --public-key-material file://~/.ssh/id_rsa.pub
eval `ssh-agent -s`

cat << EOF > ~/.ssh/config
Host *
    StrictHostKeyChecking no
EOF

#install terraform
cd /tmp
echo "installing terraform..."
curl -O https://releases.hashicorp.com/terraform/1.0.7/terraform_1.0.7_linux_amd64.zip
unzip *.zip
mv terraform /usr/local/bin/terraform
rm -f *.zip
cd /root

#install consul
cd /tmp
echo "installing consul..."
curl -O https://releases.hashicorp.com/consul/1.10.1+ent/consul_1.10.1+ent_linux_amd64.zip
unzip *.zip
mv consul /usr/local/bin/consul
rm -f *.zip
cd /root

#install vault
cd /tmp
echo "installing vault..."
curl -O https://releases.hashicorp.com/vault/1.8.2/vault_1.8.2_darwin_amd64.zip
unzip *.zip
mv vault /usr/local/bin/vault
rm -f *.zip
cd /root

#get assets
echo "cloning assets..."
git clone https://github.com/hashicorp/field-workshops-consul.git
cp -r field-workshops-consul/instruqt-tracks/consul-enterprise-on-aws/assets/terraform .
cp -r field-workshops-consul/instruqt-tracks/consul-enterprise-on-aws/assets/packer .
cp -r field-workshops-consul/instruqt-tracks/consul-enterprise-on-aws/assets/apps .
rm -rf field-workshops-consul

#provision
cd /root/terraform/vpc
echo "running terraform..."
/usr/local/bin/terraform init

exit 0
