#!/bin/bash

# Cheanup HCP

echo "Deleting HCP resources..."

if [ -f "/root/terraform/tf-deploy-hcp-consul/terraform.tfstate" ]; 
then
  echo "Deleting HCP Consul resources..."
  cd /root/terraform/tf-deploy-hcp-consul
  terraform destroy -auto-approve
fi

if [ -f "/root/terraform/tf-deploy-hcp-vault/terraform.tfstate" ]; 
then
  echo "Deleting HCP Vault resources..."
  cd /root/terraform/tf-deploy-hcp-vault
  terraform destroy -auto-approve
fi
