#!/bin/bash

#creds
vault login -method=userpass username=admin password=admin

#aws
aws_tgw=$(curl -s -H "X-Consul-Token: $(vault kv get -field master_token kv/consul)" "${CONSUL_HTTP_ADDR}/v1/health/service/aws-us-east-1-terminating-gateway?dc=aws-us-east-1&passing=true")
if [ "$(echo "${aws_tgw}" | jq '. | length')" != "1" ]; then
  fail-message "AWS TGW is not healthy"
  exit 1
fi

#azure
azure_tgw=$(curl -s -H "X-Consul-Token: $(vault kv get -field master_token kv/consul)" "${CONSUL_HTTP_ADDR}/v1/health/service/azure-west-us-2-terminating-gateway?dc=azure-west-us-2&passing=true")
if [ "$(echo "${azure_tgw}" | jq '. | length')" != "1" ]; then
  fail-message "Azure TGW is not healthy"
  exit 1
fi

exit 0
