#!/bin/bash

mkdir /root/helm
set-workdir /root/helm
cd /root/helm

endpoint=$(az resource show --ids "/subscriptions/$(az account show | jq -r .id)/resourceGroups/$(terraform output -state /root/terraform/vnet/terraform.tfstate resource_group_name)/providers/Microsoft.Solutions/applications/hcs/customconsulClusters/hashicorp-consul-cluster" --api-version 2018-09-01-preview | jq -r .properties.consulConfigFile | base64 -d | jq -r .retry_join[0])

cat << EOF > /root/helm/frontend-values.yaml
global:
  image: 'hashicorp/consul-enterprise:1.8.0-ent'
  domain: consul
  datacenter: east-us
  tls:
    enabled: true
    enableAutoEncrypt: true
    caCert:
      secretName: hashicorp-consul-ca-cert
      secretKey: tls.crt
  acls:
    manageSystemACLs: false
  gossipEncryption:
    secretName: hashicorp-consul-gossip-key
    secretKey: key
  enableConsulNamespaces: true
externalServers:
  enabled: true
  hosts: ["${endpoint}"]
  httpsPort: 443
  useSystemRoots: true
server:
  enabled: false
client:
  enabled: true
  join: ["${endpoint}"]
  extraVolumes:
  - type: 'secret'
    name: 'hashicorp-consul-acl-config'
    load: true
connectInject:
  enabled: true
  default: false
  k8sAllowNamespaces: ["default"]
  consulNamespaces:
    consulDestinationNamespace: "frontend"
  aclInjectToken:
    secretName: hashicorp-consul-connect-inject-acl-token
    secretKey: token
  overrideAuthMethodName: hashicorp-consul-k8s-auth-method
EOF

cat << EOF > /root/helm/backend-values.yaml
global:
  image: 'hashicorp/consul-enterprise:1.8.0-ent'
  domain: consul
  datacenter: east-us
  tls:
    enabled: true
    enableAutoEncrypt: true
    caCert:
      secretName: hashicorp-consul-ca-cert
      secretKey: tls.crt
  acls:
    manageSystemACLs: false
  gossipEncryption:
    secretName: hashicorp-consul-gossip-key
    secretKey: key
  enableConsulNamespaces: true
externalServers:
  enabled: true
  hosts: ["${endpoint}"]
  httpsPort: 443
  useSystemRoots: true
server:
  enabled: false
client:
  enabled: true
  join: ["${endpoint}"]
  extraVolumes:
  - type: 'secret'
    name: 'hashicorp-consul-acl-config'
    load: true
connectInject:
  enabled: true
  default: false
  k8sAllowNamespaces: ["default"]
  consulNamespaces:
    consulDestinationNamespace: "backend"
  aclInjectToken:
    secretName: hashicorp-consul-connect-inject-acl-token
    secretKey: token
  overrideAuthMethodName: hashicorp-consul-k8s-auth-method
EOF

git clone https://github.com/hashicorp/consul-helm.git
curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

exit 0
