#!/bin/bash

if [ -f /tmp/skip-check ]; then
    rm /tmp/skip-check
    exit 0
fi

kubectl config use-context eks_frontend
kubectl wait --for=condition=Ready $(kubectl get pod --selector=app=web -o name) --timeout=5s
if [ $? -ne 0 ]
then
  fail-message "Web pod not deployed."
  exit 1
fi

kubectl config use-context eks_backend
kubectl wait --for=condition=Ready $(kubectl get pod --selector=app=api -o name) --timeout=5s
if [ $? -ne 0 ]
then
  fail-message "Api pod not deployed."
  exit 1
fi

kubectl wait --for=condition=Ready $(kubectl get pod --selector=app=cache -o name) --timeout=5s
if [ $? -ne 0 ]
then
  fail-message "Cache pod not deployed."
  exit 1
fi

kubectl wait --for=condition=Ready $(kubectl get pod --selector=app=currency -o name) --timeout=5s
if [ $? -ne 0 ]
then
  fail-message "Currency pod not deployed."
  exit 1
fi

kubectl wait --for=condition=Ready $(kubectl get pod --selector=app=payments -o name) --timeout=5s
if [ $? -ne 0 ]
then
  fail-message "Payments pod not deployed."
  exit 1
fi
