#!/bin/bash

kubectl config use-context eks_frontend
kubectl apply -f frontend
kubectl wait --for=condition=Ready $(kubectl get pod --selector=app=web -o name) --timeout=60s

kubectl config use-context eks_backend
kubectl apply -f backend
kubectl wait --for=condition=Ready $(kubectl get pod --selector=app=api -o name) --timeout=60s
kubectl wait --for=condition=Ready $(kubectl get pod --selector=app=cache -o name) --timeout=60s
kubectl wait --for=condition=Ready $(kubectl get pod --selector=app=currency -o name) --timeout=60s
kubectl wait --for=condition=Ready $(kubectl get pod --selector=app=payments -o name) --timeout=60s

exit 0
