---
apiVersion: v1
kind: Service
metadata:
  name: payments-api
spec:
  selector:
    app: payments-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: payments-api
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: payments-properties-conf-v2
data:
  application.properties: |
    app.storage=redis
    app.encryption.enabled=true
    opentracing.jaeger.http-sender.url=http://jaeger-collector:14268/api/traces
    opentracing.jaeger.include-jaeger-env-tags=true
    logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG
    opentracing.jaeger.enable-b3-propagation=true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: payments-bootstrap-conf-v2
data:
  bootstrap.yaml: |
    spring:
      cloud:
        vault:
          enabled: true
          fail-fast: true
          host: vault
          port: 8200
          scheme: http
          authentication: KUBERNETES
          kubernetes:
            role: payments-api
            kubernetes-path: kubernetes
            service-account-token-file: /var/run/secrets/kubernetes.io/serviceaccount/token
          kv:
            enabled: false
          generic:
            enabled: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-api-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-api
      version: v2
  template:
    metadata:
      labels:
        app: payments-api
        version: v2
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/connect-service-upstreams: "payments-queue:6379:k8s2"
        consul.hashicorp.com/service-meta-version: v2
        consul.hashicorp.com/service-tags: v2
        consul.hashicorp.com/service-metrics-path: "/actuator/prometheus"
    spec:
      serviceAccountName: payments-api
      volumes:
        - name: properties-config
          configMap:
            name: payments-properties-conf-v2
        - name: bootstrap-config
          configMap:
            name: payments-bootstrap-conf-v2
      containers:
        - name: payments-api
          image: hashicorpdemoapp/payments:v0.0.12
          volumeMounts:
            - name: properties-config
              mountPath: /config/application.properties
              subPath: application.properties
            - name: bootstrap-config
              mountPath: /config/bootstrap.yaml
              subPath: bootstrap.yaml
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            timeoutSeconds: 1
            periodSeconds: 5
            failureThreshold: 3
            initialDelaySeconds: 30
