apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceResolver
metadata:
  name: payments-api
spec:
  defaultSubset: v1
  subsets:
    v1:
      filter: "v1 in Service.Tags"
    v2:
      filter: "v2 in Service.Tags"
