#!/bin/sh

ambassador=$(kubectl get svc -n ambassador ambassador  -o json | jq -r '.status.loadBalancer.ingress[0].ip')
api=$(curl -k -H 'Authorization: Bearer eyJhbGciOiJub25lIiwidHlwIjoiSldUIiwiZXh0cmEiOiJzbyBtdWNoIn0.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkxhbmNlIExhcnNlbiIsImlhdCI6MTU3Nzg4MDAwMCwgImF1ZCI6ICJ3ZWIifQ.' -s -o /dev/null -w "%{http_code}" https://$ambassador/web/)

if [ "$api" != "200" ]; then
  fail-message "Could not get to web service."
  exit 1
fi

exit 0
