#!/bin/bash

kubectl apply -f https://www.getambassador.io/yaml/ambassador/ambassador-rbac.yaml
kubectl apply -f https://www.getambassador.io/yaml/ambassador/ambassador-service.yaml

cat <<EOF | kubectl apply -f -
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: ambassador-admin
  name: ambassador-admin
spec:
  type: NodePort
  ports:
  - name: ambassador-admin
    port: 8877
    targetPort: 8877
    nodePort: 31877
  selector:
    service: ambassador
EOF

kubectl apply -f  https://www.getambassador.io/yaml/consul/ambassador-consul-connector.yaml

cat <<EOF | kubectl apply -f -
---
apiVersion: getambassador.io/v1
kind: TracingService
metadata:
  name: tracing
spec:
  service: "jaeger-collector:9411"
  driver: zipkin
  config: {}
EOF

#reset the error rate
sed -i 's/0.5/0.0/' /root/tracing/currency.yml
kubectl apply -f tracing

kubectl wait --for=condition=Ready $(kubectl get pod --selector=service=ambassador -o name)

exit 0
