#!/bin/sh
# solve
echo "Checking the Consul Server"

NODENAME=$(curl -s http://127.0.0.1:8500/v1/health/node/consul-server | jq -r '.[] | .Node')

if [ $NODENAME = "consul-server" ]; then
  echo "Consul is running on port 8500."
  touch /tmp/completed
  exit 0
else
  echo "Something went wrong."
  exit 1
fi