#!/bin/bash

status=$(curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1:8500/v1/agent/health/service/name/gateway)

if [ $status != "200" ]; then
  fail-message "Your gateway is not healthy."
  exit 1
fi

exit 0
