#!/bin/bash

#Get enovy for us
curl -L https://getenvoy.io/cli | bash -s -- -b /usr/local/bin
getenvoy run standard:1.14.1 -- --version
cp /root/.getenvoy/builds/standard/1.14.1/linux_glibc/bin/envoy /usr/local/bin/envoy
envoy --version

#ip
local_ipv4=$(curl -s -H "Metadata-Flavor: Google" http://metadata/computeMetadata/v1/instance/network-interfaces/0/ip)

#nmap for debug
apt update -y
apt install -y nmap

#consul
service consul stop
mkdir -p /consul/data

cat <<-EOF > /etc/consul.d/client.json
{
  "datacenter": "dc2",
  "server": false,
  "bind_addr": "${local_ipv4}",
  "client_addr": "0.0.0.0",
  "data_dir": "/consul/data",
  "log_level": "INFO",
  "node_name": "Gateway",
  "ui": true,
  "connect": {
    "enabled": true
  },
  "enable_central_service_config": true,
  "ports": {
    "grpc": 8502
  },
  "retry_join": [
    "dc2-consul-server:8301"
  ]
}
EOF

service consul start

exit 0
