---
apiVersion: v1
kind: Service
metadata:
  name: product-api
spec:
  selector:
    app: product-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: product-api
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: conf
data:
  conf.json: |
    {
    "db_connection": "host=127.0.0.1 port=5432 user=postgres password=postgres dbname=products sslmode=disable",
    "bind_address": ":8080",
    "metrics_address": ":9102"
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-api
  template:
    metadata:
      labels:
        app: product-api
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/service-metrics-port: "9102"
        consul.hashicorp.com/connect-service-upstreams: "product-db:5432:k8s2"
    spec:
      serviceAccountName: product-api
      volumes:
        - name: config
          configMap:
            name: conf
      containers:
        - name: product-api
          image: hashicorpdemoapp/product-api:v0.0.20
          volumeMounts:
            - name: config
              mountPath: /app/conf.json
              subPath: conf.json
          ports:
            - containerPort: 8080
          env:
            - name: CONFIG_FILE
              value: /app/conf.json
            - name : JAEGER_ENDPOINT
              value: http://jaeger-collector:14268/api/traces
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 2
