#!/bin/bash

#wait for azure accounts to propagate
sleep 180

#tf
export GOOGLE_CREDENTIALS=$(echo $INSTRUQT_GCP_PROJECT_CONSUL_SERVICE_ACCOUNT_KEY | base64 -d)
terraform apply -auto-approve 2>&1 | tee terraform.out

#wait
sleep 120

exit 0
