---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: emojify-payments

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emojify-payments
  labels:
    app: emojify-payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emojify-payments
  template:
    metadata:
      labels:
        app: emojify-payments
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
        "prometheus.io/scrape": "true"
        "prometheus.io/port": "9901"
    spec:
      serviceAccountName: emojify-payments
      containers:
      - name: emojify-payments
        image: nicholasjackson/emojify-payments:0.5.4
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
