---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: emojify-traffic

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emojify-traffic
  labels:
    app: emojify-traffic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emojify-traffic
  template:
    metadata:
      labels:
        app: emojify-traffic
    spec:
      serviceAccountName: emojify-traffic
      containers:
      - name: load-test
        image: nicholasjackson/emojify-traffic:v0.2.1
        env:
        - name: BASE_URI
          value: http://emojify-ingress
        - name: DURATION
          value: "24h"
        - name: SHOW_PROGRESS
          value: "false"
        - name: USERS
          value: "3"
