#!/bin/bash

#k8s ip
k8s_server_ip=$(getent ahostsv4 dc1-kubernetes |  awk '{print $1}' | head -1)
gateway_server_ip=$(getent ahostsv4 dc1-consul-gateway |  awk '{print $1}' | head -1)

#firewall
yes Y | ufw enable
ufw default allow incoming
ufw default allow outgoing
ufw deny from ${k8s_server_ip} to any port 9094
ufw deny from ${gateway_server_ip} to any port 9094
ufw status numbered
ufw status verbose
