#!/bin/bash

#jaeger
curl -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose

cat <<-EOF > /docker-compose.yml
version: '3'
services:
  jaeger:
    image: jaegertracing/all-in-one:1.13
    network_mode: "host"
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
EOF

/usr/local/bin/docker-compose up -d

exit 0
