---
apiVersion: v1
kind: Service
metadata:
  name: product-api-db
  labels:
    app: product-api-db
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: product-api-db
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: product-api-db
spec:
  protocol: "tcp"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: product-api-db
automountServiceAccountToken: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-api-db
spec:
  replicas: 1
  selector:
    matchLabels:
      service: product-api-db
      app: product-api-db
  template:
    metadata:
      labels:
        service: product-api-db
        app: product-api-db
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9102"
        consul.hashicorp.com/connect-inject: "true"
    spec:
      serviceAccountName: product-api-db
      containers:
        - name: product-api-db
          image: hashicorpdemoapp/product-api-db:v0.0.20
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: products
            - name: POSTGRES_USER
              value: product-api-db
            - name: POSTGRES_PASSWORD
              value: password
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: "pgdata"
      volumes:
        - name: pgdata
          emptyDir: {}