#!/bin/bash

kubectl apply -f fake-service
kubectl wait --for=condition=Ready $(kubectl get pod --selector=app=fake-web -o name)
kubectl wait --for=condition=Ready $(kubectl get pod --selector=app=fake-api -o name)
kubectl wait --for=condition=Ready $(kubectl get pod --selector=app=fake-cache -o name)
kubectl wait --for=condition=Ready $(kubectl get pod --selector=app=fake-payments -o name)
kubectl wait --for=condition=Ready $(kubectl get pod --selector=app=fake-currency -o name)

sleep 30

exit 0
