#!/bin/bash

kubectl apply -f emojify/resolver.yaml
kubectl apply -f emojify/splitter.yaml
kubectl apply -f emojify/router.yaml

kubectl apply -f emojify/website_v2.yml
kubectl apply -f emojify/payments.yml
kubectl wait --for=condition=Ready $(kubectl get pod --selector=app=emojify-payments -o name)

sleep 60

exit 0
