#!/bin/bash

if [ -f /tmp/skip-check ]; then
    rm /tmp/skip-check
    exit 0
fi

kubectl config use-context eks_frontend
endpoint=$(kubectl get services web -o json | jq -r .status.loadBalancer.ingress[0].hostname)

n=0
until [ $n -ge 3 ]; do
  curl --output /dev/null --silent --head --fail $endpoint && break
  n=$[$n+1]
  sleep 5
done
if [ $n -ge 3 ]; then
  fail-message "Service did not return a 200"
  exit 1
fi

exit 0
