#!/bin/bash

local_ipv4=$(curl -s -H "Metadata-Flavor: Google" http://metadata/computeMetadata/v1/instance/network-interfaces/0/ip)
nohup consul connect envoy -mesh-gateway -register \
                 -service "gateway" \
                 -address ${local_ipv4}:443 \
                 -wan-address ${local_ipv4}:443 \
                 -bind-address "public=${local_ipv4}:443" \
                 -admin-bind 127.0.0.1:19000 > /gateway.out &

exit 0
