#!/bin/bash

sleep 10
#get rg
rg=$(terraform output -state /root/terraform/vnet/terraform.tfstate resource_group_name)

#check resources
echo "Checking Vault..."
status=$(az vm show -g "${rg}" --name vault-vm | jq -r '.provisioningState')
if [ "${status}" != "Creating" ] && [ "${status}" != "Updating" ] && [ "${status}" != "Succeeded" ] ; then
  fail-message "Vault is not provisioning/provisioned. Wait a few moments and try again. Current state is: ${status}"
  exit 1
fi

echo "Checking HCS..."
if [ ! -f /root/terraform/hcs/terraform.out ]; then
    fail-message "HCS provisioning has not been started"
    exit 1
fi

exit 0
