#!/bin/bash

echo ""
echo ""
echo ">>------------------------------<<"
echo ">> Starting Core Services Setup <<"
echo ">>------------------------------<<"

set-workdir /root/terraform

cd /root/terraform/vault
terraform init

pubkey=$(cat ~/.ssh/id_rsa.pub)
cat << EOF > /root/terraform/vault/terraform.tfvars
ssh_public_key = "$(cat ~/.ssh/id_rsa.pub)"
EOF

cd /root/terraform/hcs
terraform init

#import the marketplace agreement if it exists for some reason
terraform import azurerm_marketplace_agreement.hcs "/subscriptions/${INSTRUQT_AZURE_SUBSCRIPTION_CONSUL_SUBSCRIPTION_ID}/providers/Microsoft.MarketplaceOrdering/agreements/hashicorp-4665790/offers/hcs-production/plans/on-demand-v2"

echo ""
echo ""
echo ">>------------------------------<<"
echo ">> Core Services Setup Complete <<"
echo ">>------------------------------<<"

exit 0
