#!/bin/bash

echo ""
echo ""
echo ">>--------------------------------<<"
echo ">> Core Services: Deploying Vault <<"
echo ">>--------------------------------<<"

cd /root/terraform/vault
nohup terraform apply -refresh=false -auto-approve > /root/terraform/vault/terraform.out &
sleep 10

echo ""
echo ""
echo ">>-------------------------------<<"
echo ">> Core Services: Vault Deployed <<"
echo ">>-------------------------------<<"

echo ""
echo ""
echo ">>------------------------------<<"
echo ">> Core Services: Deploying HCS <<"
echo ">>------------------------------<<"

cd /root/terraform/hcs
terraform apply -refresh=false -auto-approve > /root/terraform/hcs/terraform.out
sleep 120

echo ""
echo ""
echo ">>------------------------------<<"
echo ">> Core Services: HCS Deployed <<"
echo ">>------------------------------<<"

exit 0
