#!/bin/bash

#dir
set-workdir /root/terraform

#profile
bastion_ip=$(terraform output -state /root/terraform/vnet/terraform.tfstate bastion_ip)
echo "export bastion_ip=${bastion_ip}" >> ~/.bashrc

# add remote backend for vault setup
cat <<-EOF > /root/terraform/vault/remote_backend.tf
terraform {
  cloud {
    hostname = "app.terraform.io"
    organization = "\$ORG"
    workspaces {
      name = "provision-vault"
    }
  }
}
EOF

# add remote backend for consul setup 
cat <<-EOF > /root/terraform/consul-server/remote_backend.tf
terraform {
  cloud {
    hostname = "app.terraform.io"
    organization = "\$ORG"
    workspaces {
      name = "provision-consul-server"
    }
  }
}
EOF

exit 0
