# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cache

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache
  labels:
    app: cache
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cache
  template:
    metadata:
      labels:
        app: cache
    spec:
      serviceAccountName: cache
      containers:
      - name: cache
        image: "nicholasjackson/fake-service:v0.7.8"
        imagePullPolicy: Always
        ports:
        - containerPort: 9092
        env:
          - name: LISTEN_ADDR
            value: "0.0.0.0:9092"
          - name: MESSAGE
            value: "Cache response"
          - name: NAME
            value: "cache"
          - name: SERVER_TYPE
            value: "http"
          - name: TIMING_50_PERCENTILE
            value: "1ms"
          - name: TIMING_90_PERCENTILE
            value: "2ms"
          - name: TIMING_90_PERCENTILE
            value: "3ms"
          - name: TIMING_VARIANCE
            value: "10"
          - name: TRACING_ZIPKIN
            value: "http://jaeger-collector:9411"
