#!/bin/bash

vault login -method=userpass username=admin password=admin
export CONSUL_HTTP_TOKEN=$(vault kv get -field master_token kv/consul)

terraform apply -auto-approve | tee terraform.out
sleep 30

exit 0
