#!/bin/bash

rm -rf tracing
git clone https://github.com/hashicorp/field-workshops-consul.git
cp -r field-workshops-consul/apps/tracing .
rm -rf field-workshops-consul
rm -f tracing/currency.yml

sed -i 's/currency:9094/currency:9094:dc2/g' /root/tracing/payments.yml

jaeger_server_ip=$(getent ahostsv4 dc1-jaeger-server |  awk '{print $1}' | head -1)

sed -i "s/jaeger-collector/${jaeger_server_ip}/g" /root/tracing/web.yml
sed -i "s/jaeger-collector/${jaeger_server_ip}/g" /root/tracing/api.yml
sed -i "s/jaeger-collector/${jaeger_server_ip}/g" /root/tracing/cache.yml
sed -i "s/jaeger-collector/${jaeger_server_ip}/g" /root/tracing/payments.yml


exit 0
