#!/bin/bash

kubectl apply -f /root/tracing

kubectl wait --for=condition=Ready $(kubectl get pod --selector=app=web -o name)
kubectl wait --for=condition=Ready $(kubectl get pod --selector=app=api -o name)
kubectl wait --for=condition=Ready $(kubectl get pod --selector=app=cache -o name)
kubectl wait --for=condition=Ready $(kubectl get pod --selector=app=payments -o name)

sleep  60

exit 0
