#!/bin/bash

#creds
vault login -method=userpass username=admin password=admin
export CONSUL_HTTP_TOKEN=$(vault kv get -field master_token kv/consul)

#check the replication token
CONSUL_HTTP_TOKEN=$(vault kv get -field replication_token kv/consul) consul acl token read -self
if [ $? -ne 0 ]
then
  fail-message "Error checking relication token"
  exit 1
fi

#check on demand creds
vault read consul/creds/operator
if [ $? -ne 0 ]
then
  fail-message "Error checking operator access"
  exit 1
fi

#check the gateway defaults - http & mgw local
if [ "$(consul config read -kind proxy-defaults -name global | jq -r '.Config.protocol')" != "http" ]; then
  fail-message "Default protocol is not http"
  exit 1
fi
if [ "$(consul config read -kind proxy-defaults -name global | jq -r '.MeshGateway.Mode')" != "local" ]; then
  fail-message "MGW mode is not local"
  exit 1
fi
exit 0
