#!/bin/bash
set -euvxo pipefail

#aws
vault login -method=userpass username=admin password=admin
export CONSUL_HTTP_TOKEN=$(vault kv get -field master_token kv/consul)

#create the replication policy & token
AWS_CONSUL_IP=$(terraform output -state /root/terraform/aws-consul-primary/terraform.tfstate aws_consul_public_ip)
consul acl policy create -name operator -rules @/root/policies/consul/operator.hcl
vault secrets enable consul
vault write consul/config/access \
    address=http://${AWS_CONSUL_IP}:8500 \
    token=$(consul acl token create -description 'vault mgmt' -policy-name=global-management -format=json | jq -r '.SecretID')
vault write consul/roles/operator policies=operator ttl=30m

# Adding this to exactly mimic the instructions given in the lab
export CONSUL_HTTP_TOKEN=$(vault read -field token consul/creds/operator)
consul acl token read -self

#create the agent policy & vault role
consul acl policy create -name agent -rules @/root/policies/consul/agent.hcl
vault write consul/roles/agent policies=agent

#create the mgw policy & vault role
consul acl policy create -name mesh-gateway -rules @/root/policies/consul/mesh-gateway.hcl
vault write consul/roles/mgw policies=mesh-gateway
sleep 60

#create the replication policy & token
consul acl policy create -name replication -rules @/root/policies/consul/replication.hcl
vault write consul/roles/replication policies=replication

#create the vault policy for Vault SD registration
consul acl policy create -name vault -rules @/root/policies/consul/vault.hcl
vault write consul/roles/vault policies=vault

#mesh defaults
consul config write proxy-defaults.hcl

sleep 120

exit 0
