#!/bin/sh

ingress=$(kubectl get svc lab-consul-ingress-gateway -o json | jq -r '.status.loadBalancer.ingress[0].ip')
api=$(curl -s -o /dev/null -w "%{http_code}" http://$ingress:8080/fake-service)

if [ "$api" != "200" ]; then
  fail-message "Could not get to web service."
  exit 1
fi

exit 0
