#!/bin/bash

#reset the error rate
sed -i 's/0.5/0.0/' /root/fake-service/currency.yml
kubectl apply -f /root/fake-service

cat <<-EOF > /root/fake-web-ingress-intention.yaml
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: fake-web-ingress-intention
spec:
  destination:
    name: fake-web
  sources:
    - name: ingress-gateway
      action: allow
EOF

cat <<-EOF > /root/fake-web-ingress-gateway.hcl
Kind = "ingress-gateway"
Name = "ingress-gateway"
Listeners = [
  {
    Port = 8080
    Protocol = "http"
    Services = [
      {
        Name = "fake-service"
        Hosts = ["*"]
      }
    ]
  }
]
EOF

cat <<-EOF > /root/fake-service/fake-web-ingress-router.hcl
kind = "service-router"
name = "fake-service"
routes = [
  {
    match {
      http {
        path_prefix = "/fake-service"
      }
    }
    destination {
      service = "fake-web"
    }
  }
]
EOF

exit 0
