# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

---
nameOverride: nginx-ingress
fullnameOverride: nginx-ingress
controller:
  image:
    image: ingress-nginx/controller
    registry: k8s.gcr.io
    tag: v0.47.0
  name: controller
  podAnnotations:
    consul.hashicorp.com/connect-inject: "true"
    consul.hashicorp.com/transparent-proxy-exclude-inbound-ports: "80,8080,443,8443"
    consul.hashicorp.com/connect-service: "ingress-nginx-controller"
  admissionWebhooks:
    patch:
      podAnnotations:
        consul.hashicorp.com/connect-inject: "false"
  replicaCount: 1
  service:
    annotations:
      consul.hashicorp.com/service-sync: "true"
      consul.hashicorp.com/service-name: "nginx"
serviceAccount:
  name: ingress-nginx-controller
