#!/bin/bash

/usr/local/bin/consul catalog services -node Database | grep -q mysql
STATUS=$?

if [ $STATUS -ne 0 ]; then
  fail-message "The database service health check was not found. Please try again."
  exit 1
fi