#!/bin/bash

#metrics
cat <<-EOF > /root/prometheus-values.yaml
server:
  global:
    scrape_interval: 10s
nodeExporter:
  enabled: false
pushgateway:
  enabled: false
alertmanager:
  enabled: false
extraScrapeConfigs: |
  - job_name: 'consul'
    metrics_path: "/v1/agent/metrics"
    bearer_token: "$(kubectl get secret lab-consul-bootstrap-acl-token -o json | jq -r .data.token | base64 -d)"
    params:
      format: ['prometheus']
    scheme: http
    kubernetes_sd_configs:
    - role: pod
    relabel_configs:
    - source_labels: [__meta_kubernetes_pod_label_app]
      regex: consul
      action: keep
    - source_labels: [__meta_kubernetes_pod_label_component]
      regex: server
      action: keep
    - source_labels: [__meta_kubernetes_pod_container_port_number]
      regex: 8500
      action: keep
EOF

cat <<-EOF > /root/grafana-values.yaml
persistence:
  enabled: true
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server
        access: proxy
        isDefault: true
EOF

#Set up the UI for prometheus
cat <<EOF | kubectl apply -f -
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
  - name: http
    protocol: TCP
    port: 9090
    targetPort: 9090
    nodePort: 30090
EOF

#Set up the UI for grafana
cat <<EOF | kubectl apply -f -
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
  - name: http
    protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30030
EOF

helm repo add stable https://charts.helm.sh/stable
helm install --wait -f prometheus-values.yaml prometheus stable/prometheus
helm install --wait  -f grafana-values.yaml grafana stable/grafana --version 4.6.3

sleep 15

kubectl get secret --namespace default grafana -o jsonpath="{.data.admin-password}" | base64 --decode > /tmp/grafana-pass.txt

exit 0
