#!/bin/bash

segments_config=$(check-consul-config /etc/consul.d/zz-override.json)
if [ -z "${segments_config}" ]; then
  fail-message "Could not get segment config from cluster."
  exit 1
fi

num_segments=$(echo ${segments_config} | jq '.segments | length')
if [ ${num_segments} != "2" ]; then
  fail-message "Cluster does not have the correct number of segments."
  exit 1
fi

exit 0
