#!/bin/bash

set-workdir /root/terraform/consul

cat << EOF > /root/terraform/consul/terraform.tfvars
consul_nodes = 3
consul_cluster_version = "0.0.3"
bootstrap = false
network_segments = {
  "frontend" = "8303"
  "backend" = "8304"
}
EOF

cat << "EOF" > /root/terraform/consul/main.tf
provider "aws" {
  region  = "us-east-1"
  version = "~> 2.5"
}

data "terraform_remote_state" "vpc" {
  backend = "local"

  config = {
    path = "/root/terraform/vpc/terraform.tfstate"
  }
}

module "consul" {
  source = "./is-immutable-aws-consul"

  ami_owner     = "instruqt@hashicorp.com"
  instance_type = "t3.large"

  consul_cluster_version = var.consul_cluster_version
  bootstrap              = var.bootstrap

  enable_connect = true

  key_name    = "instruqt"
  name_prefix = "instruqt"
  vpc_id      = data.terraform_remote_state.vpc.outputs.shared_svcs_vpc
  subnets     = data.terraform_remote_state.vpc.outputs.shared_svcs_private_subnets

  region             = "us-east-1"
  availability_zones = "us-east-1a,us-east-1b,us-east-1c"

  public_ip = false

  consul_nodes     = "3"
  redundancy_zones = false
  performance_mode = false
  enable_snapshots = false

  owner = "instruqt@hashicorp.com"
  ttl   = "-1"

  additional_security_group_ids = [aws_security_group.consul_ssh.id, aws_security_group.consul_lb.id, values(aws_security_group.consul_eks)[*].id]

  consul_config = {
    "segments": [
      {
        "name": "frontend",
        "bind": "$${LOCAL_IPV4}",
        "advertise": "$${LOCAL_IPV4}",
        "port": 8303
      },
      {
        "name": "backend",
        "bind": "$${LOCAL_IPV4}",
        "advertise": "$${LOCAL_IPV4}",
        "port": 8304
      }
    ]
  }

}
EOF

exit 0
