#!/bin/bash

# Allow instruqt time to do its thing
sleep 10

eval "$(ssh-agent -s)"
ssh-add ~/.ssh/id_rsa

bastion_ip=$(terraform output -state /root/terraform/vnet/terraform.tfstate bastion_ip)
echo "export bastion_ip=${bastion_ip}" >> ~/.bashrc

cd /root/terraform/consul-tf-sync/

# add remote backend for Palo Alto Firewall setup
cat << EOF > /root/terraform/consul-tf-sync/remote_backend.tf
terraform {
  cloud {
    hostname = "app.terraform.io"
    organization = "${$ORG}"
    workspaces {
      name = "provision-consul-tf-sync"
    }
  }
}
EOF

terraform init

##creds
vault login root
vault_token=$(vault token create -field token -policy nia -period 8h -orphan)
consul_server_ip=$(terraform output -state=/root/terraform/consul-server/terraform.tfstate consul_server_ip)
vault_addr=$(terraform output -state=/root/terraform/vault/terraform.tfstate vault_lb)
bigip_mgmt_addr=$(terraform output -state=/root/terraform/bigip/terraform.tfstate mgmt_ip)
bigip_admin_user=$(terraform output -state=/root/terraform/bigip/terraform.tfstate f5_username)
vip_internal_address=$(terraform output -state=/root/terraform/bigip/terraform.tfstate vip_internal_address)
panos_mgmt_addr=$(terraform output -state=/root/terraform/panw-vm/terraform.tfstate FirewallIP)
panos_username=$(terraform output -state=/root/terraform/panw-vm/terraform.tfstate pa_username)
cat << EOF > /root/terraform/consul-tf-sync/terraform.tfvars
ssh_public_key = "$(cat ~/.ssh/id_rsa.pub)"
vip_internal_address = "${vip_internal_address}"
bigip_mgmt_addr = "${bigip_mgmt_addr}"
bigip_admin_user = "${bigip_admin_user}"
vault_addr = "${vault_addr}"
panos_mgmt_addr = "${panos_mgmt_addr}"
panos_username = "${panos_username}"
vault_token ="${vault_token}"
consul_server_ip = "${consul_server_ip}"
EOF

exit 0
