---
apiVersion: v1
kind: Service
metadata:
  name: product-db
spec:
  selector:
    app: product-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: product-db
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: product-db
spec:
  protocol: tcp
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: product-db
spec:
  serviceName: postgres-cluster
  replicas: 1
  selector:
    matchLabels:
      service: product-db
      app: product-db
  template:
    metadata:
      labels:
        service: product-db
        app: product-db
      annotations:
        consul.hashicorp.com/connect-inject: "true"
    spec:
      serviceAccountName: product-db
      containers:
        - name: product-db
          image: hashicorpdemoapp/product-api-db:v0.0.20
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: products
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: "pgdata"
  volumeClaimTemplates:
  - metadata:
      name: pgdata
      labels:
        name: postgres-cluster
      annotations:
        volume.alpha.kubernetes.io/storage-class: local-path
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
