version: "2"
containers:
- name: consul-server-0
  image: consul:latest
  ports:
  - 8300
  - 8301
  - 8302
  - 8500
  - 8600
  environment:
    CONSUL_HTTP_ADDR: http://127.0.0.1:8500
  memory: 128
- name: consul-server-2
  image: consul:latest
  ports:
  - 8300
  - 8301
  - 8302
  - 8500
  - 8600
  environment:
    CONSUL_HTTP_ADDR: http://127.0.0.1:8500
  memory: 128
- name: consul-server-1
  image: consul:latest
  ports:
  - 8300
  - 8301
  - 8302
  - 8500
  - 8600
  environment:
    CONSUL_HTTP_ADDR: http://127.0.0.1:8500
  memory: 128
- name: consul-agent-0
  image: consul:latest
  ports:
  - 8300
  - 8301
  - 8302
  - 8500
  - 8600
  environment:
    CONSUL_HTTP_ADDR: http://127.0.0.1:8500
  memory: 128
