#!/bin/bash
set -e

#install terraform
cd /tmp
echo "installing terraform..."
curl -O https://releases.hashicorp.com/terraform/0.13.2/terraform_0.13.2_linux_amd64.zip
unzip *.zip
mv terraform /usr/local/bin/terraform
rm -f *.zip
cd /root

#install consul
cd /tmp
echo "installing consul..."
curl -O https://releases.hashicorp.com/consul/1.8.0+ent/consul_1.8.0+ent_linux_amd64.zip
unzip *.zip
mv consul /usr/local/bin/consul
rm -f *.zip
cd /root

#install vault
cd /tmp
echo "installing vault..."
curl -O https://releases.hashicorp.com/vault/1.3.4/vault_1.3.4_linux_amd64.zip
unzip *.zip
mv vault /usr/local/bin/vault
rm -f *.zip
cd /root

#get assets
echo "cloning assets..."
git clone https://github.com/hashicorp/field-workshops-consul.git
cd field-workshops-consul && git checkout cts-feedback && cd ..
cp -r field-workshops-consul/instruqt-tracks/cts-beta-feedback/assets/terraform .
rm -rf field-workshops-consul

#ssh
cat << EOF > ~/.ssh/config
Host *
    StrictHostKeyChecking no
EOF
eval $(ssh-agent)
ssh-add ~/.ssh/id_rsa

#fix path
echo "export PATH=/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" >> ~/.bashrc

# Ensure we load /etc/profile.d/instruqt-env.sh
echo "source /etc/profile.d/instruqt-env.sh" >> /root/.bashrc
source /root/.bashrc

#enable marketplace
az provider register --namespace 'Microsoft.Solutions' --subscription "${INSTRUQT_AZURE_SUBSCRIPTION_CONSUL_SUBSCRIPTION_ID}"

#enable hcs ext
az extension add --source https://releases.hashicorp.com/hcs/0.3.1/hcs-0.3.1-py2.py3-none-any.whl --yes

# setup private key as TF var to make ssh easy
pubkey=$(cat ~/.ssh/id_rsa.pub)
cat << EOF > /root/terraform/base/terraform.tfvars
ssh_public_key="${pubkey}"
EOF

#provision
cd /root/terraform/base
echo "running terraform init..."
/usr/local/bin/terraform init



exit 0
