#!/bin/bash
#
# This script runs when the platform check the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#

echo "Checking HCP Auth Creds are exported"

source /root/.bashrc

if [ -n "$HCP_CLIENT_ID" ] && [ -n "$HCP_CLIENT_SECRET" ]; then 
  echo "Both HCP_CLIENT_ID and HCP_CLIENT_SECRET are set";
  exit 0
else echo "Either HCP_CLIENT_ID or HCP_CLIENT_SECRET are NOT set"; 
  fail-message "The variables HCP_CLIENT_ID and HCP_CLIENT_SECRET must be set. Please ensure you have exported them, and they have been written to ~/.bashrc as instructed."
  exit 1
fi
