#!/bin/bash

cat <<-EOF > /root/prometheus-values.yaml
server:
  global:
    scrape_interval: 10s
nodeExporter:
  enabled: false
pushgateway:
  enabled: false
alertmanager:
  enabled: false
EOF

cat <<-EOF > /root/grafana-values.yaml
persistence:
  enabled: true
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server
        access: proxy
        isDefault: true
EOF

#Set up the UI for prometheus
cat <<EOF | kubectl apply -f -
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
  - name: http
    protocol: TCP
    port: 9090
    targetPort: 9090
    nodePort: 30090
EOF

#Set up the UI for grafana
cat <<EOF | kubectl apply -f -
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: grafana
  ports:
  - name: http
    protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30030
EOF

helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm install prometheus prometheus-community/prometheus -f prometheus-values.yaml --wait --debug

helm repo add grafana https://grafana.github.io/helm-charts
helm install grafana grafana/grafana -f grafana-values.yaml --wait --debug

sleep 15

kubectl get secret --namespace default grafana -o jsonpath="{.data.admin-password}" | base64 --decode > /tmp/grafana-pass.txt

exit 0
