#!/bin/bash

cat <<-EOF > /root/prometheus-values.yaml
server:
  global:
    scrape_interval: 10s
extraScrapeConfigs: |
  - job_name: 'sample-job'
    scrape_interval: 1s
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - action: keep
        source_labels: [__meta_kubernetes_pod_container_name]
        regex: "prometheus-statsd"
EOF

cat <<-EOF > /root/grafana-values.yaml
persistence:
  enabled: true
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server
        access: proxy
        isDefault: true
EOF

#Set up the UI for prometheus
cat <<EOF | kubectl apply -f -
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
  - name: http
    protocol: TCP
    port: 9090
    targetPort: 9090
    nodePort: 30090
EOF

#Set up the UI for grafana
cat <<EOF | kubectl apply -f -
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
  - name: http
    protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30030
EOF

helm install --wait -f prometheus-values.yaml --name prometheus stable/prometheus
helm install --wait  -f grafana-values.yaml --name grafana stable/grafana --version 4.6.3

sleep 15

kubectl get secret --namespace default grafana -o jsonpath="{.data.admin-password}" | base64 --decode > /tmp/grafana-pass.txt

exit 0
