#!/bin/sh

kubectl config use-context react
endpoint=$(kubectl get svc nginx-ingress-controller -o json | jq -r .status.loadBalancer.ingress[0].ip)
cat << EOF > /etc/nginx/conf.d/app.conf
server {
  listen 8080;
  location / {
    proxy_pass http://${endpoint};
  }
  access_log /var/log/nginx/app.log;
}
EOF
/usr/sbin/service nginx restart

exit 0
