#!/bin/bash

vault login -method=userpass username=operations password=Password1
export CONSUL_HTTP_TOKEN=$(vault read -field token consul/creds/ops)

consul acl auth-method read -name hashicorp-consul-k8s-auth-method  -namespace frontend
if [ $? -ne 0 ]
then
  fail-message "Error checking frontend acl auth method"
  exit 1
fi

consul acl auth-method read -name hashicorp-consul-k8s-auth-method  -namespace backend
if [ $? -ne 0 ]
then
  fail-message "Error checking backend acl auth method"
  exit 1
fi


exit 0
