#!/bin/bash

#k8s auth methods
cat << "SCRIPT" > /usr/local/bin/setup-k8s-consul-auth
#!/bin/bash -xe

namespace=$1
kubectl config use-context eks_${namespace}

cat <<EOF | kubectl apply -f -
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hashicorp-consul-connect-injector-authmethod-svc-account
  namespace: consul
  labels:
    app: consul
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hashicorp-consul-connect-injector-authmethod-role
  namespace: consul
  labels:
    app: consul
rules:
  - apiGroups: [""]
    resources:
      - serviceaccounts
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hashicorp-consul-connect-injector-authmethod-authdelegator-role-binding
  namespace: consul
  labels:
    app: consul
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "system:auth-delegator"
subjects:
  - kind: ServiceAccount
    name: hashicorp-consul-connect-injector-authmethod-svc-account
    namespace: consul
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hashicorp-consul-connect-injector-authmethod-serviceaccount-role-binding
  namespace: consul
  labels:
    app: consul
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "hashicorp-consul-connect-injector-authmethod-role"
subjects:
  - kind: ServiceAccount
    name: hashicorp-consul-connect-injector-authmethod-svc-account
    namespace: consul
EOF

k8s_host=$(aws eks describe-cluster --name ${namespace} | jq -r .cluster.endpoint)
k8s_ca=$(aws eks describe-cluster --name ${namespace} | jq -r .cluster.certificateAuthority.data | base64 -d)

k8s_sa=$(kubectl  get sa -n consul hashicorp-consul-connect-injector-authmethod-svc-account -o json | jq -r .secrets[0].name)
k8s_jwt=$(kubectl get secrets -n consul ${k8s_sa} -o json | jq -r .data.token | base64 -d)

consul acl auth-method create -type "kubernetes" \
    -name "hashicorp-consul-k8s-auth-method" \
    -namespace "${namespace}" \
    -description "k8s auth" \
    -kubernetes-host "${k8s_host}" \
    -kubernetes-ca-cert "${k8s_ca}" \
    -kubernetes-service-account-jwt "${k8s_jwt}"

consul acl binding-rule create -method 'hashicorp-consul-k8s-auth-method' \
    -namespace "${namespace}" \
    -description 'apps' \
    -bind-type 'service' \
    -bind-name '${serviceaccount.name}' \
    -selector 'serviceaccount.namespace==default'
SCRIPT
chmod +x /usr/local/bin/setup-k8s-consul-auth
