#!/bin/bash

kubectl config use-context frontend-aks
JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}' \
 && kubectl get nodes -o jsonpath="$JSONPATH" | grep "Ready=True"
if [ $? -ne 0 ]
then
 fail-message "Frontend AKS nodes not ready"
 exit 1
fi

kubectl config use-context backend-aks
JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}' \
 && kubectl get nodes -o jsonpath="$JSONPATH" | grep "Ready=True"
if [ $? -ne 0 ]
then
 fail-message "Backend AKS nodes not ready"
 exit 1
fi

exit 0
