#!/bin/bash

kubectl config use-context k8s1
kubectl apply -f v2
sleep 5
kubectl wait pod --for=condition=Ready --selector=app=payments-api,version=v2 --timeout 90s
cat <<EOF | kubectl apply -f -
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceSplitter
metadata:
  name: payments-api
spec:
  splits:
    - weight: 0
      serviceSubset: v1
    - weight: 100
      serviceSubset: v2
EOF
sleep 10


exit 0
