#!/bin/bash

if [ -f /tmp/skip-check ]; then
    rm /tmp/skip-check
    exit 0
fi

#check the pods
kubectl wait --for=condition=Ready $(kubectl get pod --selector=app=web -o name) --timeout=5s
if [ $? -ne 0 ]
then
  fail-message "Web pod not deployed."
  exit 1
fi
kubectl wait --for=condition=Ready $(kubectl get pod --selector=app=api -o name) --timeout=5s
if [ $? -ne 0 ]
then
  fail-message "Api pod not deployed."
  exit 1
fi
kubectl wait --for=condition=Ready $(kubectl get pod --selector=app=cache -o name) --timeout=5s
if [ $? -ne 0 ]
then
  fail-message "Cache pod not deployed."
  exit 1
fi
kubectl wait --for=condition=Ready $(kubectl get pod --selector=app=payments -o name) --timeout=5s
if [ $? -ne 0 ]
then
  fail-message "Payments pod not deployed."
  exit 1
fi

#check the bigip service is up - we should get a 503 at this point
app=$(terraform output -state /root/terraform/bigip/terraform.tfstate app_url)
n=0
until [ $n -ge 3 ]; do
  status=$(curl --output /dev/null --silent --head -w "%{http_code}" ${app})
  if [ "${status}" = "503" ]; then
    break
  fi
  n=$[$n+1]
  echo "retrying api..."
  sleep 5
done
if [ $n -ge 3 ]; then
  echo "Logging a BIG-IP API status response for debug: $(curl --output /dev/null --silent --head --fail -w "%{http_code}" ${app})"
  echo "Logging a verbose API request for debug..."
  response=$(curl -v --silent ${app})
  echo ${response}
  fail-message "Service did not return an expected 503. Check BIG-IP."
  exit 1
fi

exit 0
