#!/bin/bash

if [ -f /tmp/skip-check ]; then
    rm /tmp/skip-check
    exit 0
fi

#check the pods
kubectl wait --for=condition=Ready $(kubectl get pod --selector=app=web -o name) --timeout=5s
if [ $? -ne 0 ]
then
  fail-message "Web pod not deployed."
  exit 1
fi
kubectl wait --for=condition=Ready $(kubectl get pod --selector=app=api -o name) --timeout=5s
if [ $? -ne 0 ]
then
  fail-message "Api pod not deployed."
  exit 1
fi
kubectl wait --for=condition=Ready $(kubectl get pod --selector=app=cache -o name) --timeout=5s
if [ $? -ne 0 ]
then
  fail-message "Cache pod not deployed."
  exit 1
fi
kubectl wait --for=condition=Ready $(kubectl get pod --selector=app=payments -o name) --timeout=5s
if [ $? -ne 0 ]
then
  fail-message "Payments pod not deployed."
  exit 1
fi

#check the bigip service is up - we should get a 503 at this point
ambassador=$(terraform output -state /root/terraform/bigip/terraform.tfstate app_url)
api=$(curl -ks -o /dev/null -w "%{http_code}" $ambassador)

if [ "$api" != "503" ]; then
  fail-message "Could not get to Ambassador backend gateway. Check your BIG-IP. Status code is: ${api}"
  exit 1
fi

exit 0
