#!/bin/bash

backend=$(aws eks describe-cluster --name backend | jq -r .cluster.status)
if [ ${backend} != "ACTIVE" ]; then
  fail-message "Backend EKS cluster did not provision. Current state is: ${backend}"
  exit 1
fi

frontend=$(aws eks describe-cluster --name frontend | jq -r .cluster.status)
if [ ${frontend} != "ACTIVE" ]; then
  fail-message "Frontend EKS cluster did not provision. Current state is: ${frontend}"
  exit 1
fi

exit 0
