#!/bin/bash

frontend=$(aws eks describe-cluster --name frontend | jq -r .cluster.status)
if [ "${frontend}" != "ACTIVE" ]; then
  fail-message "Frontend EKS cluster did not provision. Current state is: ${frontend}"
  exit 1
fi

if [[ ! -f /root/terraform/eks/kubeconfig_frontend ]]
then
    fail-message "Frontend kube config file not found."
    exit 1
fi

backend=$(aws eks describe-cluster --name backend | jq -r .cluster.status)
if [ "${backend}" != "ACTIVE" ]; then
  fail-message "Backend EKS cluster did not provision. Current state is: ${backend}"
  exit 1
fi

if [[ ! -f /root/terraform/eks/kubeconfig_backend ]]
then
    fail-message "Backend kube config file not found."
fi

exit 0
