#!/bin/bash

set-workdir /root/terraform/eks

cd /root/terraform/eks
/usr/local/bin/terraform init

#iam authenticator
curl -o aws-iam-authenticator https://amazon-eks.s3.us-west-2.amazonaws.com/1.15.10/2020-02-22/bin/linux/amd64/aws-iam-authenticator
chmod +x aws-iam-authenticator
mv aws-iam-authenticator /usr/local/bin/aws-iam-authenticator

exit 0
