#!/bin/bash

#route propagation from TGW
sleep 60

set-workdir /root/terraform/eks

#iam authenticator
curl -o aws-iam-authenticator https://amazon-eks.s3.us-west-2.amazonaws.com/1.15.10/2020-02-22/bin/linux/amd64/aws-iam-authenticator
chmod +x aws-iam-authenticator
mv aws-iam-authenticator /usr/local/bin/aws-iam-authenticator

cd /root/terraform/eks
terraform init

exit 0
