#!/bin/bash

#check leader
leader=$(curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1:8500/v1/status/leader?dc=k8s2)
if [ "$leader" != "200" ]; then
  fail-message "Your Consul cluster is does not have a leader."
  exit 1
fi

exit 0
