#!/bin/bash

kubectl config use-context frontend-aks
app=$(kubectl get services web -o json | jq -r .status.loadBalancer.ingress[0].ip)
cat << EOF > /etc/nginx/conf.d/app.conf
server {
  listen 9090;
  location / {
    proxy_pass http://$app;
  }
  access_log /var/log/nginx/app.log;
}
EOF
service nginx restart

exit 0
