# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: currency

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency
  labels:
    app: currency
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency
  template:
    metadata:
      labels:
        app: currency
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
    spec:
      serviceAccountName: currency
      containers:
      - name: currency
        image: "nicholasjackson/fake-service:v0.7.8"
        imagePullPolicy: Always
        ports:
        - containerPort: 9094
        env:
          - name: LISTEN_ADDR
            value: "0.0.0.0:9094"
          - name: MESSAGE
            value: "Hello from Currency POD"
          - name: NAME
            value: "currency"
          - name: SERVER_TYPE
            value: "http"
          - name: ERROR_RATE
            value: "0.0"
          - name: ERROR_CODE
            value: "500"
          - name: ERROR_TYPE
            value: "http_error"
          - name: TRACING_ZIPKIN
            value: "http://jaeger-collector:9411"
