#!/bin/sh

#Path
echo "Fixing our path..."
export PATH=/sbin:/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin

#Utils
apt-get update -y && apt-get install -y curl xz-utils lsb-release software-properties-common

# ENVOY - ALTERNATIVE INSTALLATION METHOD
ENVOY_VERSION="1.18.3"
wget https://archive.tetratelabs.io/envoy/download/v${ENVOY_VERSION}/envoy-v${ENVOY_VERSION}-linux-amd64.tar.xz
tar -xf envoy-v${ENVOY_VERSION}-linux-amd64.tar.xz
chmod +x envoy-v${ENVOY_VERSION}-linux-amd64/bin/envoy
mv envoy-v${ENVOY_VERSION}-linux-amd64/bin/envoy /usr/bin/envoy
rm -rf envoy-v${ENVOY_VERSION}-linux-amd64.tar.xz envoy-v${ENVOY_VERSION}-linux-amd64
envoy --version

#consul
rm -f /usr/local/bin/consul
curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
apt-get update -y && apt-get install -y consul=1.10.0
rm -f /etc/consul.d/consul.hcl

# Creating the Consul client config
cat <<-EOF > /etc/consul.d/client.json
{
  "datacenter": "dc1",
  "bind_addr": "0.0.0.0",
  "client_addr": "0.0.0.0",
  "data_dir": "/consul/data",
  "log_level": "INFO",
  "node_name": "Database",
  "server": false,
  "ui": false,
  "leave_on_terminate": false,
  "skip_leave_on_interrupt": true,
  "rejoin_after_leave": true,
  "connect": {
    "enabled": true
  },
  "ports": {
    "grpc": 8502
  },
  "retry_join": [
    "consul-server-0:8301",
    "consul-server-1:8301",
    "consul-server-2:8301"
  ]
}
EOF

cat <<-EOF > /etc/consul.d/database_service.json
{
  "service": {
    "name": "mysql",
    "tags": [
      "database",
      "production"
    ],
    "port": 3306,
    "check": {
      "id": "mysql",
      "name": "MySQL TCP on port 3306",
      "tcp": "localhost:3306",
      "interval": "10s",
      "timeout": "1s"
    }
  }
}
EOF

echo "Killing the currently running Consul agent..."
pkill consul

echo "Creating Consul startup script..."
cat <<-EOF > /bin/start_consul.sh
#!/bin/sh
echo "Starting HashiCorp Consul in client Mode..."
sleep 1
echo "CMD: nohup consul agent -config-dir=/etc/consul.d > /consul.out &"
nohup /usr/bin/consul agent -config-dir=/etc/consul.d > /consul.out &
echo "Log output will appear in consul.out..."
sleep 1
echo "Consul client startup complete."
EOF

chmod +x /bin/start_consul.sh
/bin/start_consul.sh

exit 0
