#!/bin/sh

cat <<-EOF > /etc/consul.d/database_service.json
{
  "service": {
    "name": "mysql",
    "tags": [
      "database",
      "production"
    ],
    "port": 3306,
    "connect": { "sidecar_service": {} },
    "check": {
      "id": "mysql",
      "name": "MySQL TCP on port 3306",
      "tcp": "localhost:3306",
      "interval": "10s",
      "timeout": "1s"
    }
  }
}
EOF

/usr/bin/consul reload

sleep 10

exit 0
