#!/bin/bash

vault login -method=userpass username=operations password=Password1

rg=$(terraform output -state /root/terraform/vnet/terraform.tfstate resource_group_name)
kubectl config use-context frontend-aks
setup-k8s-consul-secrets ${rg} hcs hashicorp-consul-cluster $(vault kv get -field gossip_key secret/consul) $(vault read -field token consul/creds/frontend-agent) $(vault read -field token consul/creds/k8s-injector) "$(vault kv get -field ca secret/consul)"
kubectl config use-context backend-aks
setup-k8s-consul-secrets ${rg} hcs hashicorp-consul-cluster $(vault kv get -field gossip_key secret/consul) $(vault read -field token consul/creds/backend-agent) $(vault read -field token consul/creds/k8s-injector) "$(vault kv get -field ca secret/consul)"

exit 0
