#!/bin/sh

firewall_ip=$(terraform output -state /root/terraform/panw-vm/terraform.tfstate FirewallIP)
pa_username=$(terraform output -state /root/terraform/panw-vm/terraform.tfstate pa_username)
pa_password=$(terraform output -state /root/terraform/panw-vm/terraform.tfstate pa_password)

pa_virtual_systems=$(curl -sk -o /dev/null  -u ${pa_username}:${pa_password} -w ''%{http_code}'' https://${firewall_ip}/restapi/v9.1/Device/VirtualSystems)
if [ "${pa_virtual_systems}" != "200" ]; then
  fail-message "Palo Alto VM Series Firewall 'base configuration' not applied. "
  exit 1
fi

exit 0
