#!/bin/bash

#check that we have principal created
terraform output payments_identity_principal_id
if [ $? -ne 0 ]
then
  fail-message "Could not get payments principal from terraform."
  exit 1
fi

#check the consul policies are correct
consul acl policy read -name payments-policy
if [ $? -ne 0 ]
then
  fail-message "Could not get payment acl policy"
  exit 1
fi
consul acl role read -name payments-role
if [ $? -ne 0 ]
then
  fail-message "Could not get payment acl role"
  exit 1
fi
consul acl auth-method read -name azure
if [ $? -ne 0 ]
then
  fail-message "Could not get azure jwt consul auth method"
  exit 1
fi
#consul acl binding-rule read -name payments-role

#check that we have an azure vault role
vault read auth/azure/role/consul
if [ $? -ne 0 ]
then
  fail-message "Could not get azure vault role"
  exit 1
fi
exit 0
