#!/bin/bash

# Allow instruqt time to do its thing
sleep 10

eval "$(ssh-agent -s)"
ssh-add ~/.ssh/id_rsa

bastion_ip=$(terraform output -state /root/terraform/vnet/terraform.tfstate bastion_ip)
echo "export bastion_ip=${bastion_ip}" >> ~/.bashrc

cd /root/terraform/consul-tf-sync/
terraform init

##creds
vault login -method=userpass username=operations password=Password1
export CONSUL_HTTP_TOKEN=$(vault read -field token consul/creds/ops)
consul_server_ip=$(terraform output -state /root/terraform/consul-server/terraform.tfstate consul_server_ip)

bigip_mgmt_addr=$(terraform output -state=/root/terraform/bigip/terraform.tfstate mgmt_ip)
bigip_admin_user=$(terraform output -state=/root/terraform/bigip/terraform.tfstate f5_username)
bigip_admin_passwd=$(terraform output -state=/root/terraform/bigip/terraform.tfstate f5_password)
vip_internal_address=$(terraform output -state=/root/terraform/bigip/terraform.tfstate vip_internal_address)
panos_mgmt_addr=$(terraform output -state=/root/terraform/panw-vm/terraform.tfstate FirewallIP)
panos_username=$(terraform output -state=/root/terraform/panw-vm/terraform.tfstate pa_username)
panos_password=$(terraform output -state=/root/terraform/panw-vm/terraform.tfstate pa_password)

cat << EOF > /root/terraform/consul-tf-sync/terraform.tfvars
ssh_public_key = "$(cat ~/.ssh/id_rsa.pub)"
vip_internal_address = "${vip_internal_address}"
bigip_mgmt_addr = "${bigip_mgmt_addr}"
bigip_admin_user = "${bigip_admin_user}"
bigip_admin_passwd = "${bigip_admin_passwd}"
panos_mgmt_addr = "${panos_mgmt_addr}"
panos_username = "${panos_username}"
panos_password = "${panos_password}"
consul_server_ip = "${consul_server_ip}"
EOF

exit 0
