#!/bin/bash

#creds
vault login -method=userpass username=admin password=admin

#aws
gcp_frontend=$(curl -s -H "X-Consul-Token: $(vault kv get -field master_token kv/consul)" "${CONSUL_HTTP_ADDR}/v1/health/service/frontend?dc=gcp-us-central-1&passing=true")
if [ "$(echo "${gcp_frontend}" | jq '. | length')" != "1" ]; then
  fail-message "GCP frontend is not healthy"
  exit 1
fi

gcp_public_api=$(curl -s -H "X-Consul-Token: $(vault kv get -field master_token kv/consul)" "${CONSUL_HTTP_ADDR}/v1/health/service/public-api?dc=gcp-us-central-1&passing=true")
if [ "$(echo "${gcp_public_api}" | jq '. | length')" != "1" ]; then
  fail-message "GCP public-api is not healthy"
  exit 1
fi

exit 0
