#!/bin/bash

consul config write trace.hcl

consul intention create -allow app-frontend app-api
consul intention create -allow app-api app-cache
consul intention create -allow app-api app-payments
consul intention create -allow app-payments app-currency

exit 0
