#!/bin/bash

consul config write trace.hcl

kubectl apply -f tracing

consul intention create -allow web api
consul intention create -allow api cache
consul intention create -allow api payments
consul intention create -allow payments currency

exit 0
