#!/bin/bash

#ui access
consul_lb=$(terraform output -state /root/terraform/consul-primary/terraform.tfstate aws_consul_public_ip)
echo "export CONSUL_HTTP_ADDR=http://${consul_lb}:8500" >> ~/.bashrc
cat << EOF > /etc/nginx/conf.d/consul.conf
server {
  listen 8500;
  location / {
    proxy_pass https://${consul_lb};
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_redirect off;
  }
  access_log /var/log/nginx/consul.log;
}
EOF
/usr/sbin/service nginx restart

exit 0
