#!/bin/bash

#aws
AWS_VAULT_IP=$(terraform output -state /root/terraform/vault/terraform.tfstate aws_vault_ip)
export VAULT_ADDR=http://${AWS_VAULT_IP}:8200
export VAULT_TOKEN=$(cat /root/aws_vault_keys.json | jq -r .root_token)
export CONSUL_HTTP_ADDR="http://$(terraform output -state /root/terraform/aws-consul-primary/terraform.tfstate aws_consul_public_ip):8500"
export CONSUL_HTTP_TOKEN=$(vault kv get -field master_token kv/consul)

#create the replication token
echo 'operator = "write"
agent_prefix "" {
  policy = "read"
}
node_prefix "" {
  policy = "write"
}
acl = "write"
service_prefix "" {
  policy = "read"
  intentions = "read"
}' |  consul acl policy create -name replication -rules -

#create the consul token with the seeded secret
consul acl token create -policy-name replication -secret=$(vault kv get -field replication_token kv/consul)

#mesh defaults
echo '
Kind      = "proxy-defaults"
Name      = "global"
Namespace = "default"
Config {
  protocol = "http"
}
MeshGateway {
   Mode = "local"
}' | consul config write -

exit 0
