#!/bin/sh

token=$(kubectl get secret lab-consul-bootstrap-acl-token -o json | jq -r .data.token | base64 -d)
leader=$(curl -s -H "X-Consul-Token: ${token}" -o /dev/null -w "%{http_code}" http://127.0.0.1:30085/v1/operator/raft/configuration)
if [ "$leader" != "200" ]; then
  fail-message "Your Consul cluster is not deployed."
  exit 1
fi

exit 0
