#!/bin/bash

#path
echo "export PATH=/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" >> ~/.bashrc

#Azure CLI
curl -sL https://aka.ms/InstallAzureCLIDeb | bash

#ssh
eval `ssh-agent -s`

cat << EOF > ~/.ssh/config
Host *
    StrictHostKeyChecking no
EOF

#install terraform
cd /tmp
echo "installing terraform..."
curl -O https://releases.hashicorp.com/terraform/0.12.23/terraform_0.12.23_linux_amd64.zip
unzip *.zip
mv terraform /usr/local/bin/terraform
rm -f *.zip
cd /root

#install consul
cd /tmp
echo "installing consul..."
curl -O https://releases.hashicorp.com/consul/1.7.3+ent/consul_1.7.3+ent_linux_amd64.zip
unzip *.zip
mv consul /usr/local/bin/consul
rm -f *.zip
cd /root

#install vault
cd /tmp
echo "installing vault..."
curl -O https://releases.hashicorp.com/vault/1.3.4/vault_1.3.4_linux_amd64.zip
unzip *.zip
mv vault /usr/local/bin/vault
rm -f *.zip
cd /root

#get assets
echo "cloning assets..."
git clone -b add-consul-instruqt-hcs-azure-track https://github.com/hashicorp/field-workshops-consul.git
cp -r field-workshops-consul/instruqt-tracks/consul-hcs-on-azure/assets/terraform .
cp -r field-workshops-consul/instruqt-tracks/consul-hcs-on-azure/assets/apps .
rm -rf field-workshops-consul

#provision
cd /root/terraform/vnet
echo "running terraform..."
/usr/local/bin/terraform init

#assignment
set-workdir /root/terraform/vnet
cd /root/terraform/vnet

pubkey=$(cat ~/.ssh/id_rsa.pub)
cat << EOF > /root/terraform/vnet/terraform.tfvars
ssh_public_key="${pubkey}"
EOF

exit 0
