#!/bin/bash

set-workdir /root/apps/nomad

NOMAD_IP=$(terraform output -state /root/terraform/nomad-scheduler-services/terraform.tfstate aws_nomad_server_public_ip)
echo "export NOMAD_ADDR=http://${NOMAD_IP}:4646" >> ~/.bashrc

exit 0
