#!/bin/bash

set-workdir /root/terraform/nomad-scheduler-services

NOMAD_IP=$(terraform output -state /root/terraform/nomad-scheduler-services/terraform.tfstate aws_nomad_server_public_ip)
echo "export NOMAD_ADDR=http://${NOMAD_IP}:4646" >> ~/.bashrc

cat << 'EOF' > /root/terraform/nomad-scheduler-services/payments.hcl
job "payments" {
  datacenters = ["aws-us-east-1"]
  group "payments" {
    count = 1
    network {
      mode = "bridge"
    }
    service {
      name = "payments"
      port = "8080"
      connect {
        sidecar_service {
          proxy {
            upstreams {
              destination_name = "redis"
              local_bind_port  = 6379
            }
            upstreams {
              destination_name = "vault"
              local_bind_port  = 8200
            }
          }
        }
      }
    }
    task "payments" {
      driver = "docker"
      config {
        image = "hashicorpdemoapp/payments:latest"
        mounts = [
          {
            type   = "bind"
            source = "local/bootstrap.yml"
            target = "/bootstrap.yml"
          },
          {
            type   = "bind"
            source = "local/application.properties"
            target = "/application.properties"
          }
        ]
      }
      vault {
        policies = ["payments"]
      }
      template {
        data = <<EOH
---
spring:
  cloud:
    vault:
      enabled: true
      fail-fast: true
      authentication: TOKEN
      token: ${VAULT_TOKEN}
      host: localhost
      port: 8200
      scheme: http
        EOH
        destination = "local/bootstrap.yml"
      }
      template {
        data = <<EOH
app.storage=redis
app.encryption.enabled=true
app.encryption.path=transit
app.encryption.key=payments
spring.redis.host=localhost
spring.redis.port=6379
        EOH
        destination = "local/application.properties"
      }
    }
  }
}
EOF

exit 0
