#!/bin/bash

#context
kubectl config use-context k8s1

kubectl wait pod --for=condition=Ready --selector=app=frontend
if [ $? -ne 0 ]
then
  fail-message "Frontend pod not deployed."
  exit 1
fi
kubectl wait pod --for=condition=Ready --selector=app=public-api
if [ $? -ne 0 ]
then
  fail-message "Public API pod not deployed."
  exit 1
fi
kubectl wait pod --for=condition=Ready --selector=app=product-api
if [ $? -ne 0 ]
then
  fail-message "Product API pod not deployed."
  exit 1
fi
kubectl wait pod --for=condition=Ready --selector=app=payments-api,version=v1
if [ $? -ne 0 ]
then
  fail-message "Payment API V1 pod not deployed."
  exit 1
fi

exit 0
