#!/bin/bash

kubectl config use-context k8s1
helm install -f /root/helm/k8s1-consul-values.yaml consul hashicorp/consul  --wait --debug --version "0.32.0-beta3"
kubectl apply -f deployments/config/proxy-defaults.yml
sleep 15

exit 0
