#!/bin/bash

set-workdir /root/terraform

cd /root/terraform/aks
terraform init

cd /root/terraform/vault
terraform init

pubkey=$(cat ~/.ssh/id_rsa.pub)
cat << EOF > /root/terraform/vault/terraform.tfvars
ssh_public_key="${pubkey}"
EOF

cd /root/terraform/vgw
cat << EOF > /root/terraform/vgw/terraform.tfvars
remote_gateways=false
EOF

exit 0
