#!/bin/bash

cd /root/terraform/gcp-consul-secondary
terraform init

set-workdir /root/terraform/gcp-consul-secondary

cat << EOF > /root/terraform/gcp-consul-secondary/terraform.tfvars
gcp_project_id="$(echo $INSTRUQT_GCP_PROJECT_CONSUL_PROJECT_ID)"
EOF

#helm3
curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
helm repo add hashicorp https://helm.releases.hashicorp.com

exit 0
