#!/bin/bash

#export NOMAD_ADDR=http://3.90.57.60:4646

mkdir /root/nomad
cat << EOF > /root/nomad/payments.hcl
job "payments" {
  datacenters = ["aws-us-east-1"]
  group "payments" {
    count = 2
    network {
      mode = "bridge"
    }
    service {
      name = "payments"
      connect {
        sidecar_service {
          proxy {
            upstreams {
              destination_name = "redis"
              local_bind_port  = 6379
            }
          }
        }
      }
    }
    task "payments" {
      driver = "docker"
      config {
        image = "hashicorpdemoapp/frontend:latest"
      }
    }
  }
}
EOF

exit 0
