#!/bin/bash

cd /root/terraform/vault
set-workdir /root/terraform/vault

#ui access
vault_lb=$(terraform output -state /root/terraform/vault/terraform.tfstate aws_vault_ip)
echo "export VAULT_ADDR=http://${vault_lb}:8200" >> ~/.bashrc
cat << EOF > /etc/nginx/conf.d/vault.conf
server {
  listen 8200;
  location / {
    proxy_pass http://${vault_lb}:8200;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_redirect off;
  }
  access_log /var/log/nginx/vault.log;
}
EOF
/usr/sbin/service nginx reload

#init the Vault clusters
chmod +x /root/scripts/setup_vault.sh
chmod +x /root/scripts/reset_vault.sh
/root/scripts/setup_vault.sh

exit 0
