#!/bin/bash

#login
AWS_VAULT_IP=$(terraform output -state /root/terraform/vault/terraform.tfstate aws_vault_ip)
export VAULT_ADDR=http://${AWS_VAULT_IP}:8200
export VAULT_TOKEN=$(cat /root/aws_vault_keys.json | jq -r .root_token)

#seed vault with consul bootstrap secrets
vault kv put kv/consul master_token=$(cat /proc/sys/kernel/random/uuid) replication_token=$(cat /proc/sys/kernel/random/uuid) gossip_key=$(consul keygen) ttl=5m

exit 0
