#!/bin/bash

#login
vault login -method=userpass username=admin password=admin

#seed vault with consul bootstrap secrets
vault kv put kv/consul \
  master_token=$(cat /proc/sys/kernel/random/uuid) \
  gossip_key=$(consul keygen) \
  ttl=5m

#auto config support
vault write /auth/aws/config/identity iam_metadata=client_arn
vault write identity/oidc/key/consul allowed_client_ids=consul-server-aws-us-east-1,consul-server-azure-west-us-2
vault write identity/oidc/role/consul-aws-us-east-1 key=consul client_id=consul-server-aws-us-east-1 template='{"consul": {"node_arn": {{identity.entity.aliases.'$(vault auth list -format=json | jq -r '."aws/".accessor')'.metadata.client_arn}} } }'
vault write identity/oidc/role/consul-azure-west-us-2 key=consul client_id=consul-server-azure-west-us-2 template='{"consul": {"node_vm": {{identity.entity.aliases.'$(vault auth list -format=json | jq -r '."azure/".accessor')'.metadata.vm_name}} } }'

#wait for restart
sleep 120

exit 0
