#!/bin/bash

status=$(curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1:8500/v1/agent/health/service/name/currency-sidecar-proxy)

if [ $status != "200" ]; then
  fail-message "Your sidecar is not running."
  exit 1
fi

exit 0
