#!/bin/bash

#deploy vault - run this twice to fix Azure
terraform apply -auto-approve 2>&1 | tee terraform.out
terraform apply -auto-approve 2>&1 | tee terraform.out

#wait for Vault
sleep 180

exit 0
