---
apiVersion: v1
kind: ConfigMap
metadata:
  name: emojify-website-configmap-v1
data:
  config: |
    window.env = {};
    window.env.config = {
      AUTH_URL: '/auth',
      API_URL: '/api/',
      HOME_URL: '/',
      PAYMENT_URL: '/api/payments',
      PAYMENT_ENABLED: false,
      OAUTH_ENABLED: false,
      AUTH_DISABLED: true
    };

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emojify-website-v1
  labels:
    app: emojify-website
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emojify-website
      version: v1
  template:
    metadata:
      labels:
        app: emojify-website
        version: v1
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
        "consul.hashicorp.com/service-tags": "v1"
        "prometheus.io/scrape": "true"
        "prometheus.io/port": "9901"
    spec:
      volumes:
      - name: config
        configMap:
          name: emojify-website-configmap-v1
          items:
          - key: config
            path: env.js
      serviceAccountName: emojify-website
      containers:
      - name: emojify-website
        image: "nicholasjackson/emojify-website:v0.8.0"
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config
          mountPath: /usr/share/nginx/html/config
          readOnly: true
