#!/bin/sh

api=$(curl -s -o /dev/null -w "%{http_code}" 'http://localhost:30000/api/payments'  -H 'content-type: application/json;charset=UTF-8' --data-binary '{"name":"Mr Paul Banks","number":"5355 1234 4231 1234","cvc":"123","expiry":"10/20"}' --compressed)

if [ "$api" != "200" ]; then
  fail-message "Could not access emojify payments."
  exit 1
fi

exit 0
