#!/bin/bash

if [ -f /tmp/skip-check ]; then
    rm /tmp/skip-check
    exit 0
fi

#check the bigip service is up - we should get a 200 at this point
ambassador=$(terraform output -state /root/terraform/bigip/terraform.tfstate app_url)
api=$(curl -s -o /dev/null -w "%{http_code}" $ambassador)

if [ "$api" != "200" ]; then
  fail-message "Could not reach the app through BIG-IP. BIG-IP returned status code: ${api}"
  exit 1
fi

exit 0
