#!/bin/bash

cd /root/terraform/bigip
set-workdir /root/terraform/bigip

#app_lb=$(terraform output -state /root/terraform/bigip/terraform.tfstate ambassador_url)
#cat << EOF > /etc/nginx/conf.d/ambassador.conf
#server {
#  listen 443;
#  location / {
#    proxy_pass ${app_lb};
#    proxy_set_header X-Real-IP \$remote_addr;
#    proxy_redirect off;
#    proxy_http_version 1.1;
#    proxy_set_header Upgrade \$http_upgrade;
#    proxy_set_header Connection "Upgrade";
#    proxy_set_header Host \$host;
#  }
#  access_log /var/log/nginx/consul.log;
#}
#EOF
#/usr/sbin/service nginx restart

exit 0
