#!/bin/bash

#fix path
echo "export PATH=/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" >> ~/.bashrc

#install kubectl
export DEBIAN_FRONTEND=noninteractive
apt update -y
apt install -y apt-transport-https ca-certificates curl vim openssh-client git jq gnupg2 lsb-release software-properties-common
curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
add-apt-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" |  tee /etc/apt/sources.list.d/kubernetes.list
apt update -y
apt install -y kubectl consul vault
setcap cap_ipc_lock= /usr/bin/vault

#disable host checks
cat << EOF > ~/.ssh/config
Host *
    StrictHostKeyChecking no
EOF

#get the kube configs
ssh k8s1 'cat ~/.kube/config' > /tmp/k8s1_kube_config.yaml
ssh k8s2 'cat ~/.kube/config' > /tmp/k8s2_kube_config.yaml

#name them - k8s1
sed -i 's/default/k8s1/g' /tmp/k8s1_kube_config.yaml
sed -i 's/127.0.0.1/k8s1/g' /tmp/k8s1_kube_config.yaml
#name them - k8s2
sed -i 's/default/k8s2/g' /tmp/k8s2_kube_config.yaml
sed -i 's/127.0.0.1/k8s2/g' /tmp/k8s2_kube_config.yaml

#merge them & set the context
mkdir -p ~/.kube/
KUBECONFIG=/tmp/k8s1_kube_config.yaml:/tmp/k8s2_kube_config.yaml kubectl config view --merge --flatten > ~/.kube/config
kubectl config use-context k8s1

#helm install
curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
/usr/local/bin/helm repo add hashicorp https://helm.releases.hashicorp.com

#assets
git clone -b track-life-of-a-developer https://github.com/hashicorp/field-workshops-consul.git
cp -r field-workshops-consul/instruqt-tracks/consul-life-of-a-developer/assets/config /root/
cp -r field-workshops-consul/instruqt-tracks/consul-life-of-a-developer/assets/deployments /root/
cp -r field-workshops-consul/instruqt-tracks/consul-life-of-a-developer/assets/helm /root/
rm -rf /root/field-workshops-consul

#nginx
export DEBIAN_FRONTEND=noninteractive
apt update -y
apt install -y nginx
cat << EOF > /etc/nginx/conf.d/consul.conf
server {
  listen 8500;
  location / {
    proxy_pass https://k8s1:30085;
    proxy_ssl_verify off;
  }
  access_log /var/log/nginx/consul.log;
}
EOF
/usr/sbin/service nginx restart

#deploy vault & set up transit
kubectl config use-context k8s1
helm install vault hashicorp/vault -f /root/helm/vault-values.yaml
export VAULT_ADDR=http://k8s1:30020
vault login root
vault secrets enable transit
vault write -f transit/keys/payments

exit 0
