#!/bin/sh
#
# This script runs when the platform setup the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#

echo "Initializing terraform for HCP Consul deployment challenge"

cd /root/terraform/tf-deploy-ecs-services/
terraform init

set-workdir /root/terraform/tf-deploy-ecs-services

exit 0
