#!/bin/bash

set-workdir /root/terraform/consul
cd /root/terraform/consul
terraform init

consul_lb=$(terraform output -state /root/terraform/consul/terraform.tfstate consul_ip)
echo "export CONSUL_HTTP_ADDR=http://${consul_lb}" >> ~/.bashrc

#get the upgrade utility
cd /tmp
curl -L -O https://github.com/krarey/azure-cluster-upgrade/releases/download/v0.0.2/azure-cluster-upgrade_v0.0.2_linux_amd64.tar.gz
tar -xvzf *.tar.gz
mv azure-cluster-upgrade /usr/local/bin/azure-cluster-upgrade
cd -

pubkey=$(cat ~/.ssh/id_rsa.pub)
cat << EOF > /root/terraform/consul/terraform.tfvars
location = "eastus"
image_resource_group = "llarsen-instruqt-resources"
ssh_public_key="${pubkey}"

consul_cluster_version = "0.0.2"
bootstrap = false
EOF

cat << 'EOF' >> /root/terraform/consul/main.tf

resource "null_resource" "consul-upgrade" {
  depends_on = [module.consul]
  provisioner "local-exec" {
    command = "azure-cluster-upgrade -r ${module.consul.consul_rg} -v ${module.consul.consul_vmss} -s ${data.azurerm_subscription.current.subscription_id}"
  }
}
EOF

exit 0
