#!/bin/bash

if [ -f /tmp/skip-check ]; then
    rm /tmp/skip-check
    exit 0
fi

vault login -method=userpass username=operations password=Password1
vault read consul/creds/ops

if [ $? -ne 0 ]
then
  fail-message "Could not get ops cred."
  exit 1
fi

exit 0
