#!/bin/bash

set-workdir /root/terraform/vault

cd /root/terraform/vault
terraform init
terraform apply -auto-approve

sleep 60

vault_lb=$(terraform output -state /root/terraform/vault/terraform.tfstate lb)
echo "export VAULT_ADDR=http://${vault_lb}" >> ~/.bashrc
cat << EOF > /etc/nginx/conf.d/vault.conf
server {
  listen 8200;
  location / {
    proxy_pass http://${vault_lb};
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_redirect off;
  }
  access_log /var/log/nginx/vault.log;
}
EOF
consul_lb=$(terraform output -state /root/terraform/consul/terraform.tfstate lb)
cat << EOF > /etc/nginx/conf.d/consul.conf
server {
  listen 8500;
  location / {
    proxy_pass http://${consul_lb};
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_redirect off;
  }
  access_log /var/log/nginx/consul.log;
}
EOF
/usr/sbin/service nginx restart

#inital vault
export VAULT_ADDR=http://${vault_lb}
master_token=$(terraform output -state /root/terraform/consul/terraform.tfstate master_token)
agent_server_token=$(terraform output -state /root/terraform/consul/terraform.tfstate agent_server_token)
gossip_key=$(terraform output -state /root/terraform/consul/terraform.tfstate gossip_key)

vault login root
vault kv put secret/consul master_token=${master_token} agent_server_token=${agent_server_token} gossip_key=${gossip_key}

vault auth enable userpass
vault write auth/userpass/users/operations password=Password1 policies=ops token_ttl=8h
vault write auth/userpass/users/backend password=Password1 policies=backend token_ttl=30m
vault secrets enable consul

echo 'path "secret/*" {
  capabilities = ["list"]
}
path "secret/data/consul" {
  capabilities = ["read"]
}
path "consul/*"
{
  capabilities = ["create", "read", "update", "delete"]
}' | vault policy write ops -

echo 'path "consul/creds/backend-developer"
{
  capabilities = ["read"]
}' | vault policy write backend -

unset VAULT_TOKEN
exit 0
