#!/bin/bash

/usr/local/bin/vault login -method=userpass username=operations password=Password1
export CONSUL_HTTP_TOKEN=$(/usr/local/bin/vault kv get -field=master_token secret/consul)
vault_consul_mgmt_token=$(/usr/local/bin/consul acl token create -policy-name=global-management -description "vault mgmt" | grep SecretID | cut -d ":" -f2 | xargs)

/usr/local/bin/consul acl policy create -name "ops" -description "admin policy for ops" -rules 'acl = "write" operator = "write" namespace_prefix "" {acl = "write"}'
/usr/local/bin/vault write consul/roles/ops policies=ops ttl=1h

/usr/local/bin/vault write consul/config/access address=${CONSUL_HTTP_ADDR} token=${vault_consul_mgmt_token}


exit 0
