#!/bin/bash

# Wait for the Instruqt host bootstrap to finish
until [ -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
    sleep 1
done

# Wait for the Kubernetes API server to become available
while ! curl --silent --fail --output /dev/null http://localhost:8001/api
do
    sleep 1
done

# Enable bash completion for kubectl
echo "source /usr/share/bash-completion/bash_completion" >> /root/.bashrc
echo "complete -F __start_kubectl k" >> /root/.bashrc

#dashboard token
kubectl get secret -n kubernetes-dashboard $(kubectl get sa -n kubernetes-dashboard admin-user -o json | jq -r .secrets[0].name) -o json | jq -r .data.token | base64 -d > /root/dashboard-token.txt

exit 0
