#!/bin/bash

cd /root/terraform/aws-consul-primary
terraform init

set-workdir /root/terraform/aws-consul-primary

pubkey=$(cat ~/.ssh/id_rsa.pub)
cat << EOF > /root/terraform/aws-consul-primary/terraform.tfvars
ssh_public_key="${pubkey}"
EOF

exit 0
