#!/bin/bash

#wait for AWS LB DNS
sleep 180

#App UI
kubectl config use-context eks_frontend
app=$(kubectl get services web -o json | jq -r .status.loadBalancer.ingress[0].hostname)
cat << EOF > /etc/nginx/conf.d/app.conf
server {
  listen 8080;
  location / {
    proxy_pass http://${app};
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_redirect off;
  }
  access_log /var/log/nginx/app.log;
}
EOF

/usr/sbin/service nginx restart

exit 0
