#!/bin/bash

vault login -method=userpass username=operations password=Password1
export CONSUL_HTTP_TOKEN=$(vault read -field token consul/creds/ops)

vault write consul/roles/frontend-developer policies=frontend-developer-policy ttl=1h
vault write consul/roles/backend-developer  policies=backend-developer-policy  ttl=1h

vault kv patch secret/consul k8s_injector=$(consul acl token create -description 'k8s injector' -policy-name 'k8s-injector-policy' -format=json | jq -r .SecretID)
vault kv patch secret/consul frontend_agent_token=$(consul acl token create -description 'frontend agent' -policy-name 'frontend-agent-policy' -format=json | jq -r .SecretID)
vault kv patch secret/consul backend_agent_token=$(consul acl token create -description 'backend agent' -policy-name 'backend-agent-policy' -format=json | jq -r .SecretID)

exit 0
