#!/bin/bash

mkdir /root/helm
set-workdir /root/helm
cd /root/helm

instruqt_env=$(terraform output -state /root/terraform/consul/terraform.tfstate env)

cat << EOF > /root/helm/frontend-values.yaml
global:
  tls:
    enabled: false
  image: 'hashicorp/consul-enterprise:1.7.2-ent'
  domain: consul
  datacenter: us-east-1
  bootstrapACLs: true
  gossipEncryption:
    secretName: hashicorp-consul-gossip-key
    secretKey: key
  enableConsulNamespaces: true
server:
  enabled: false
client:
  enabled: true
  join: ["provider=aws tag_key=Environment-Name tag_value=${instruqt_env}-consul"]
  extraConfig: |
    {
      "segment": "frontend",
      "ports": {
        "serf_lan": 8303
        }
    }
ui:
  enabled: true
connectInject:
  enabled: true
  default: false
  k8sAllowNamespaces: ["default"]
  consulNamespaces:
    consulDestinationNamespace: "frontend"
EOF

cat << EOF > /root/helm/backend-values.yaml
global:
  tls:
    enabled: false
  image: 'hashicorp/consul-enterprise:1.7.2-ent'
  domain: consul
  datacenter: us-east-1
  bootstrapACLs: true
  gossipEncryption:
    secretName: hashicorp-consul-gossip-key
    secretKey: key
  enableConsulNamespaces: true
server:
  enabled: false
client:
  enabled: true
  join: ["provider=aws tag_key=Environment-Name tag_value=${instruqt_env}-consul"]
  extraConfig: |
    {
      "segment": "backend",
      "ports": {
        "serf_lan": 8304
        }
    }
ui:
  enabled: true
connectInject:
  enabled: true
  default: false
  k8sAllowNamespaces: ["default"]
  consulNamespaces:
    consulDestinationNamespace: "backend"
EOF

git clone https://github.com/hashicorp/consul-helm.git
curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

exit 0
