#!/bin/bash

#login
AWS_VAULT_IP=$(terraform output -state /root/terraform/vault/terraform.tfstate aws_vault_ip)
export VAULT_ADDR=http://${AWS_VAULT_IP}:8200
export VAULT_TOKEN=$(cat /root/aws_vault_keys.json | jq -r .root_token)

#create secrets eng
vault auth enable aws
vault auth enable azure
vault auth enable gcp
vault write auth/azure/config \
    tenant_id="$(az account show | jq -r .tenantId)" \
    resource="https://management.azure.com/"

vault secrets enable -version=2 kv
vault secrets enable pki

#set up CA
vault write pki/root/generate/internal \
    common_name="HashiCorp CA" \
    ttl=8760h
vault write pki/roles/consul \
    allowed_domains=consul \
    allow_subdomains=true \
    max_ttl=72h

#set up policy for consul
echo 'path "kv/*"
{
  capabilities = ["read"]
}
path "pki/*"
{
  capabilities = ["read","update"]
}' | vault policy write consul -

#set up policy for product-api
echo 'path "kv/*"
{
  capabilities = ["read"]
}
path "pki/*"
{
  capabilities = ["read","update"]
}' | vault policy write product-api -

#Set up trust with Vault for Consul Servers & Applications
AWS_CONSUL_IAM_ROLE_ARN=$(terraform output -state /root/terraform/iam/terraform.tfstate aws_consul_iam_role_arn)
vault write auth/aws/role/consul auth_type=iam \
  bound_iam_principal_arn="${AWS_CONSUL_IAM_ROLE_ARN}" \
  policies=consul ttl=30m
AZURE_CONSUL_SERVICE_PRINCIPAL_ID=$(terraform output -state /root/terraform/iam/terraform.tfstate azure_consul_user_assigned_identity_principal_id)
vault write auth/azure/role/consul \
  policies=consul \
  bound_service_principal_ids="${AZURE_CONSUL_SERVICE_PRINCIPAL_ID}"
GCP_CONSUL_SERVICE_ACCOUNT=$(terraform output -state /root/terraform/iam/terraform.tfstate gcp_consul_service_account_email)
vault write auth/gcp/role/consul \
  type="iam" \
  policies="consul" \
  bound_service_accounts="${GCP_CONSUL_SERVICE_ACCOUNT}"
AZURE_PRODUCT_API_SERVICE_PRINCIPAL_ID=$(terraform output -state /root/terraform/iam/terraform.tfstate azure_product_api_user_assigned_identity_principal_id)
vault write auth/azure/role/product-api \
  policies=product-api \
  bound_service_principal_ids="${AZURE_PRODUCT_API_SERVICE_PRINCIPAL_ID}"

#seed vault with consul bootsrap secrets
vault kv put kv/consul master_token=$(cat /proc/sys/kernel/random/uuid) replication_token=$(cat /proc/sys/kernel/random/uuid) gossip_key=$(consul keygen)

exit 0
