#!/bin/bash

#login
AWS_VAULT_IP=$(terraform output -state /root/terraform/vault/terraform.tfstate aws_vault_ip)
export VAULT_ADDR=http://${AWS_VAULT_IP}:8200
export VAULT_TOKEN=$(cat /root/aws_vault_keys.json | jq -r .root_token)

#set up policy for consul
echo 'path "kv/*"
{
  capabilities = ["read"]
}
path "pki/*"
{
  capabilities = ["read","update"]
}' | vault policy write consul -

#set up policy for product-api
echo 'path "kv/*"
{
  capabilities = ["read"]
}
path "pki/*"
{
  capabilities = ["read","update"]
}' | vault policy write product-api -

#vault trust
AWS_VAULT_IAM_ROLE_ARN=$(terraform output -state /root/terraform/vault/terraform.tfstate aws_vault_iam_role_arn)
vault write auth/aws/role/vault \
  auth_type=iam \
  bound_iam_principal_arn="${AWS_VAULT_IAM_ROLE_ARN}" \
  policies=admin ttl=30m
AZURE_VAULT_SERVICE_PRINCIPAL_ID=$(terraform output -state /root/terraform/vault/terraform.tfstate azure_vault_user_assigned_identity_principal_id)
vault write auth/azure/role/vault \
  bound_service_principal_ids="${AZURE_VAULT_SERVICE_PRINCIPAL_ID}" \
  policies=admin ttl=30m

#consul trust
AWS_CONSUL_IAM_ROLE_ARN=$(terraform output -state /root/terraform/iam/terraform.tfstate aws_consul_iam_role_arn)
vault write auth/aws/role/consul auth_type=iam \
  bound_iam_principal_arn="${AWS_CONSUL_IAM_ROLE_ARN}" \
  policies=consul ttl=30m
AZURE_CONSUL_SERVICE_PRINCIPAL_ID=$(terraform output -state /root/terraform/iam/terraform.tfstate azure_consul_user_assigned_identity_principal_id)
vault write auth/azure/role/consul \
  policies=consul \
  bound_service_principal_ids="${AZURE_CONSUL_SERVICE_PRINCIPAL_ID}"

#nomad trust
AWS_NOMAD_IAM_ROLE_ARN=$(terraform output -state /root/terraform/iam/terraform.tfstate aws_nomad_iam_role_arn)
vault write auth/aws/role/nomad auth_type=iam \
  bound_iam_principal_arn="${AWS_NOMAD_IAM_ROLE_ARN}" \
  policies=nomad-server,admin ttl=30m

#app trust
AZURE_PRODUCT_API_SERVICE_PRINCIPAL_ID=$(terraform output -state /root/terraform/iam/terraform.tfstate azure_product_api_user_assigned_identity_principal_id)
vault write auth/azure/role/product-api \
  policies=product-api \
  bound_service_principal_ids="${AZURE_PRODUCT_API_SERVICE_PRINCIPAL_ID}"

#seed vault with consul bootstrap secrets
vault kv put kv/consul master_token=$(cat /proc/sys/kernel/random/uuid) replication_token=$(cat /proc/sys/kernel/random/uuid) gossip_key=$(consul keygen) ttl=5m

exit 0
