#!/bin/bash

#login
AWS_VAULT_IP=$(terraform output -state /root/terraform/vault/terraform.tfstate aws_vault_ip)
export VAULT_ADDR=http://${AWS_VAULT_IP}:8200
export VAULT_TOKEN=$(cat /root/aws_vault_keys.json | jq -r .root_token)

#create secrets
vault auth enable aws
vault secrets enable -version=2 kv
vault secrets enable pki

exit 0
