#!/bin/bash

cd /root/terraform/iam
terraform init

set-workdir /root/terraform/iam

cat << EOF > /root/terraform/iam/terraform.tfvars
gcp_project_id="$(echo $INSTRUQT_GCP_PROJECT_CONSUL_PROJECT_ID)"
EOF

exit 0
