#!/bin/bash

if [ -f /tmp/skip-check ]; then
    rm /tmp/skip-check
    exit 0
fi

# azure resources
rg=$(terraform output -state /root/terraform/vnet/terraform.tfstate resource_group_name)
echo "Checking vault instance"
status=$(az vm get-instance-view -g $rg --name vault-vm | jq -r .provisioningState)
echo $status
if [ "${status}" != "Succeeded" ] ; then
  fail-message "Vault instance is not provisioned. Wait a few moments and try again. Current state is: ${status}"
  exit 1
fi

# this is broken for now
#echo "Checking HCS cluster"
#status=$(az hcs list -g ${rg} | jq -r '.[0].provisioningState')
#echo $status
#if [ "${status}" != "Succeeded" ] ; then
#  fail-message "HCS cluster is not provisioned. Wait a few moments and try again. Current state is: ${status}"
#  exit 1
#fi

#terraform outputs
url=$(terraform output -state /root/terraform/bigip/terraform.tfstate -json | jq -r .mgmt_url.value)
echo "F5 Management URL is: $url"
if [ -z "${url}" ] || [ "${url}" = "null" ]; then
  fail-message "BIG-IP is not provisoned yet"
  exit 1
fi

#vault
vault_lb=$(terraform output -state /root/terraform/vault/terraform.tfstate vault_lb)
echo "Vault Load balancer is: $vault_lb"
if [ -z "${vault_lb}" ]; then
  fail-message "Vault is not provisioned yet"
  exit 1
fi
vault_api=$(curl -s -o /dev/null -w "%{http_code}" http://{$vault_lb}/v1/sys/health)
if [ "${vault_api}" != "200" ]; then
  fail-message "Vault service did not return a 200. Please wait a few moments and try again."
  exit 1
fi

#hcs
consul_lb=$(terraform output -state /root/terraform/hcs/terraform.tfstate consul_url)
echo "Consul Load balancer is: $consul_lb"
if [ -z "${consul_lb}" ]; then
  fail-message "Consul is not provisioned yet"
  exit 1
fi
consul_api=$(curl -s -o /dev/null -w "%{http_code}" {$consul_lb}/v1/status/leader)
if [ "${consul_api}" != "200" ]; then
  fail-message "Consul service did not return a 200. Please wait a few moments and try again."
  exit 1
fi

exit 0
