#!/bin/bash
# This is the setup script for the workstation container. Use it to set the stage for your terraform training, demo, or lab.
set -e

# Allow instruqt time to do its thing
sleep 10

cat << EOF > /root/terraform/legacy/terraform.tfvars
ssh_public_key = "$(ssh-keygen -i -m pkcs8 -f ~/.ssh/id_rsa.pub)"
EOF

consul_lb=$(terraform output -state /root/terraform/hcs/terraform.tfstate consul_url)
echo "export CONSUL_HTTP_ADDR=${consul_lb}" >> ~/.bashrc
