#!/bin/bash
# This is the setup script for the workstation container. Use it to set the stage for your terraform training, demo, or lab.
set -e

set-workdir /root/terraform/legacy

cd /root/terraform/bigip
terraform output > /info.txt

cd /root/terraform/legacy
terraform init

# Allow instruqt time to do its thing
sleep 10

app_lb=$(terraform output -state /root/terraform/bigip/terraform.tfstate app_url)
cat << EOF > /etc/nginx/conf.d/app.conf
server {
  listen 9090;
  location / {
    proxy_pass ${app_lb};
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_redirect off;
  }
  access_log /var/log/nginx/consul.log;
}
EOF
/usr/sbin/service nginx restart


cat << EOF > /root/terraform/legacy/terraform.tfvars
ssh_public_key = "$(ssh-keygen -i -m pkcs8 -f ~/.ssh/id_rsa.pub)"
EOF

consul_lb=$(terraform output -state /root/terraform/hcs/terraform.tfstate consul_url)
echo "export CONSUL_HTTP_ADDR=${consul_lb}" >> ~/.bashrc

exit 0
