#!/bin/bash

cd /root/terraform/legacy
terraform apply -auto-approve > /root/terraform/legacy/terraform.out

cd /root/terraform/legacy/as3
terraform apply -auto-approve >  /root/terraform/legacy/as3/terraform.out

sleep 60

exit 0 