#!/bin/bash

#check db
export PGPASSWORD=$(terraform output -state /root/terraform/database-services/terraform.tfstate postgres_password)
psql -U postgres@$(terraform output -state /root/terraform/infra/terraform.tfstate env) \
  -d postgres \
  -h $(terraform output -state /root/terraform/database-services/terraform.tfstate postgres_fqdn) \
  -c 'SELECT * FROM coffees' \
  -a

#check queue
ssh -i ~/.ssh/id_rsa ubuntu@$(terraform output -state /root/terraform/tgw/terraform.tfstate aws_tgw_public_ip) \
  "redis-cli -h \
  $(terraform output -state /root/terraform/cache-services/terraform.tfstate -json aws_elasticache_cache_nodes | jq -r .[0].address) -p 6379 keys '*'"

exit 0
