#!/bin/bash

#context
kubectl config use-context k8s1

#chaos
kubectl exec deploy/payments-api-v1 -c payments-api -- apk add curl
kubectl exec deploy/payments-api-v1 -c payments-api -- curl -s -X POST localhost:8080/actuator/chaosmonkey/enable
sleep 15

#scale
kubectl scale deployment.v1.apps/payments-api-v1 --replicas=2
sleep 60

#restart
kubectl rollout restart deployment/payments-api-v1

exit 0
