#!/bin/bash

cd /root/terraform/scheduler-services
terraform init

cat << EOF > /root/terraform/scheduler-services/terraform.tfvars
gcp_project_id="$(echo $INSTRUQT_GCP_PROJECT_CONSUL_PROJECT_ID)"
EOF

set-workdir /root/terraform/scheduler-services

exit 0
