#!/bin/bash

vault_lb=$(terraform output -state /root/terraform/vault/terraform.tfstate lb)
echo "export VAULT_ADDR=http://${vault_lb}" >> ~/.bashrc
cat << EOF > /etc/nginx/conf.d/vault.conf
server {
  listen 8200;
  location / {
    proxy_pass http://${vault_lb};
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_redirect off;
  }
  access_log /var/log/nginx/vault.log;
}
EOF
consul_lb=$(terraform output -state /root/terraform/consul/terraform.tfstate lb)
cat << EOF > /etc/nginx/conf.d/consul.conf
server {
  listen 8500;
  location / {
    proxy_pass https://${consul_lb};
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_redirect off;
  }
  access_log /var/log/nginx/consul.log;
}
EOF
/usr/sbin/service nginx restart
