#!/bin/bash

#provison Vault in the background
cd /root/terraform/vault
#terraform init
nohup terraform apply -auto-approve > /root/terraform/vault/terraform.out &

#provison EKS clusters in the background
cd /root/terraform/eks
#terraform init
nohup terraform apply -auto-approve > /root/terraform/eks/terraform.out &

sleep 30

exit 0
