#!/bin/bash

#creds
vault login -method=userpass username=admin password=admin
export CONSUL_HTTP_TOKEN=$(vault read -field token consul/creds/operator)

#tf
terraform apply -auto-approve 2>&1 | tee terraform.out
sleep 60

exit 0
