#!/bin/bash

cd /root/terraform/bigip
terraform apply -refresh=false -auto-approve > /root/terraform/bigip/terraform.out

#block HCS
while [ -f /root/terraform/hcs/.terraform.tfstate.lock.info ]; do echo 'hcs still provisioning'; sleep 5;  done
sleep 30
exit 0
