#!/bin/bash

# let instruqt do its thing
sleep 10

cd /root/terraform/bigip
terraform apply -auto-approve > /root/terraform/bigip/terraform.out 

#block HCS
while [ -f /root/terraform/hcs/.terraform.tfstate.lock.info ]; do echo 'hcs still provisioning'; sleep 5;  done
exit 0