#!/bin/bash

vault login -method=userpass username=backend password=Password1
export CONSUL_HTTP_TOKEN=$(vault read -field token consul/creds/backend-developer)

consul intention create --allow frontend/web backend/api
consul intention create --allow backend/api backend/cache
consul intention create --allow backend/api backend/payments
consul intention create --allow backend/payments backend/currency

exit 0
