#!/bin/bash

#assignment
set-workdir /root/terraform/vnet

cat << EOF > /root/terraform/vnet/remote_backend.tf
terraform {
  cloud {
    hostname = "app.terraform.io"
    organization = "\$ORG"
    workspaces {
      name = "provision-vnets"
    }
  }
}
EOF

exit 0
