#!/bin/bash

#context
kubectl config use-context k8s1

#check our routes
if [ "$(consul config read -kind service-router -name hashicups  | jq -r '.Routes[0].Destination.Service')" != "public-api" ]; then
  fail-message "Public API route is not set."
  exit 1
fi

if [ "$(consul config read -kind service-router -name hashicups  | jq -r '.Routes[1].Destination.Service')" != "frontend" ]; then
  fail-message "Frontend route is not set."
  exit 1
fi

exit 0
