#!/bin/bash

#Consul
service consul stop
local_ipv4=$(curl -s -H "Metadata-Flavor: Google" http://metadata/computeMetadata/v1/instance/network-interfaces/0/ip)

mkdir -p /consul/data

cat <<-EOF > /etc/consul.d/server.json
{
  "datacenter": "dc2",
  "primary_datacenter": "dc1",
  "bind_addr": "${local_ipv4}",
  "client_addr": "0.0.0.0",
  "data_dir": "/consul/data",
  "log_level": "INFO",
  "node_name": "ConsulServer",
  "server": true,
  "ui": true,
  "bootstrap_expect": 1,
  "leave_on_terminate": false,
  "skip_leave_on_interrupt": true,
  "rejoin_after_leave": true,
  "connect": {
    "enabled": true
  }
}
EOF

service consul start

exit 0
