#!/bin/bash

#Service is unhealthy passing in DC1 #TODO
#status=$(curl -s 'http://127.0.0.1:8500/v1/health/service/currency?passing=true&dc=dc1')

#Service is passing in DC2
status=$(curl -s -o /dev/null -w "%{http_code}" 'http://127.0.0.1:8500/v1/health/service/currency?passing=true&dc=dc2')
if [ $status != "200" ]; then
  fail-message "Service in DC2 did not return a 200."
  exit 1
fi

#App works
status=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:30900)
if [ $status != "200" ]; then
  fail-message "App did not return a 200."
  exit 1
fi

exit 0
