#!/bin/bash

kubectl apply -f tracing
sleep 30

cat <<EOF | consul config write -
kind            = "service-resolver"
name            = "currency"
connect_timeout = "3s"
failover = {
  "*" = {
    datacenters = ["dc2"]
  }
}
EOF
consul config read -kind service-resolver -name currency

kubectl delete -f tracing/currency.yml
sleep 30

exit 0
