#!/bin/bash

#k8s setup
echo "Setting up K8s..."
until [ -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
    sleep 1
done
echo "source /usr/share/bash-completion/bash_completion" >> /root/.bashrc
echo "complete -F __start_kubectl k" >> /root/.bashrc
/usr/bin/start.sh
echo "K8s setup complete"

#get the consul binary
curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
apt install consul -y

#consul ui
cat <<EOF | kubectl apply -f -
---
apiVersion: v1
kind: Service
metadata:
  name: consul-service
spec:
  type: NodePort
  selector:
    app: consul
    component: server
  ports:
  - name: http
    protocol: TCP
    port: 8500
    targetPort: 8500
    nodePort: 30085
EOF

#consul helm
helm repo add hashicorp https://helm.releases.hashicorp.com
cat <<-EOF > /root/consul-values.yaml
global:
  datacenter: dc1
  acls:
    manageSystemACLs: true
server:
  replicas: 1
  bootstrapExpect: 1
  extraConfig: |
    {
      "telemetry": {
        "prometheus_retention_time": "8h",
        "disable_hostname": true
      },
      "ui_config": {
        "enabled": true,
        "metrics_provider": "prometheus",
        "metrics_proxy": {
          "base_url": "http://prometheus-server"
        }
      }
    }
client:
  enabled: true
ui:
  enabled: true
controller:
  enabled: true
syncCatalog:
  enabled: true
  toConsul: true
  toK8S: false
  default: false
connectInject:
  enabled: true
  default: false
ingressGateways:
  enabled: true
  defaults:
    replicas: 1
    service:
      type: LoadBalancer
      ports:
        - port: 8080
EOF

exit 0
