#!/bin/bash

#ip
service consul stop
local_ipv4=$(curl -H "Metadata-Flavor: Google" http://metadata/computeMetadata/v1/instance/network-interfaces/0/ip)

#consul
mkdir -p /consul/data

cat <<-EOF > /etc/consul.d/client.json
{
  "datacenter": "dc2",
  "server": false,
  "bind_addr": "${local_ipv4}",
  "client_addr": "0.0.0.0",
  "data_dir": "/consul/data",
  "log_level": "INFO",
  "node_name": "Currency",
  "ui": true,
  "connect": {
    "enabled": true
  },
  "enable_central_service_config": true,
  "ports": {
    "grpc": 8502
  },
  "retry_join": [
    "dc2-consul-server:8301"
  ]
}
EOF
service consul start

#app
curl -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose

jaeger_server_ip=$(getent ahostsv4 dc1-jaeger-server |  awk '{print $1}' | head -1)

cat <<-EOF > /docker-compose.yml
version: '3'
services:
  currency:
    network_mode: "host"
    environment:
      LISTEN_ADDR: 0.0.0.0:9094
      MESSAGE: "Currency response"
      NAME: "currency"
      SERVER_TYPE: "http"
      TRACING_ZIPKIN: "http://${jaeger_server_ip}:9411"
    image: "nicholasjackson/fake-service:v0.6.3"
EOF

/usr/local/bin/docker-compose up -d

exit 0
