#!/bin/bash

cat <<-EOF > /etc/consul.d/currency-service.json
{
  "service": {
    "name": "currency",
    "tags": [
      "production"
    ],
    "port": 9094,
    "check": {
      "id": "http",
      "name": "traffic on port 9094",
      "http": "http://127.0.0.1:9094/health",
      "interval": "10s",
      "timeout": "1s"
    }
  }
}
EOF

consul reload

exit 0
