#!/bin/sh

cat <<-EOF > /etc/consul.d/application_service.json
{
  "service": {
    "name": "wordpress",
    "tags": [
      "wordpress",
      "production"
    ],
    "port": 80,
    "connect": {
      "sidecar_service": {
        "proxy": {
          "upstreams": [
            {
              "destination_name": "mysql",
              "local_bind_port": 3306
            }
          ]
        }
      }
    },
    "check": {
      "id": "wordpress",
      "name": "wordpress TCP on port 80",
      "tcp": "localhost:80",
      "interval": "10s",
      "timeout": "1s"
    }
  }
}
EOF

/usr/bin/consul reload

sleep 10

exit 0
