#!/bin/bash


rg=$(terraform output -state /root/terraform/vnet/terraform.tfstate resource_group_name)

echo "checking frontend vnet remote gateway..."
status=$(az network vnet peering list --resource-group ${rg} --vnet-name frontend-vnet | jq -r '.[0].useRemoteGateways')
echo ${status}
if [ "${status}" != "true" ] ; then
  fail-message "Remote gateway not enabled for frontend-vnet"
  exit 1
fi

echo "checking backend vnet remote gateway..."
status=$(az network vnet peering list --resource-group ${rg} --vnet-name backend-vnet | jq -r '.[0].useRemoteGateways')
echo ${status}
if [ "${status}" != "true" ] ; then
  fail-message "Remote gateway not enabled for backend-vnet"
  exit 1
fi

exit 0
