#!/bin/bash

set-workdir /root/terraform

cd /root/terraform/aks
terraform init

cd /root/terraform/vault
terraform init
pubkey=$(cat ~/.ssh/id_rsa.pub)
cat << EOF > /root/terraform/vault/terraform.tfvars
ssh_public_key = <<EOT
${pubkey}
EOT
EOF

cd /root/terraform/hcs
terraform init

exit 0
