#!/bin/bash

set-workdir /root/terraform

cd /root/terraform/aks
terraform init

cd /root/terraform/vault
terraform init

#test with dummy key
pubkey=$(cat ~/.ssh/id_rsa.pub)
cat << EOF > /root/terraform/vault/terraform.tfvars
ssh_public_key = "$(ssh-keygen -i -m pkcs8 -f ~/.ssh/id_rsa.pub)"
EOF

cd /root/terraform/hcs
terraform init

exit 0
