---
apiVersion: v1
kind: Service
metadata:
  name: ambassador
  namespace: ambassador
  annotations:
    consul.hashicorp.com/service-sync: 'true'
    consul.hashicorp.com/service-name: ambassador
  labels:
    product: aes
    app.kubernetes.io/component: ambassador-service
    cis.f5.com/as3-tenant: Consul_SD
    cis.f5.com/as3-app: Ambassador
    cis.f5.com/as3-pool: gateway_pool
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: http
  selector:
    service: ambassador
