kind: ConfigMap
apiVersion: v1
metadata:
  name: f5-ambassador
  namespace: default
  labels:
    f5type: virtual-server
    as3: 'true'
data:
  template: |
    {
      "class": "AS3",
      "action": "deploy",
      "persist": true,
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.20.0",
        "id": "urn:uuid:33045210-3ab8-4636-9b2a-c98d22ab915d",
        "label": "http",
        "remark": "Ambassador example",
        "Consul_SD": {
          "class": "Tenant",
          "Ambassador": {
            "class": "Application",
            "WAF_Policy": {
              "class": "WAF_Policy",
              "url": "https://raw.githubusercontent.com/hashicorp/field-workshops-consul/master/instruqt-tracks/f5-hashicorp-app-mod-tf-consul/assets/terraform/legacy/as3/templates/asm_policy.xml",
              "ignoreChanges": false,
              "enforcementMode": "blocking"
            },
            "template": "http",
            "Ambassador_VIP": {
              "class": "Service_HTTP",
              "virtualPort": 8080,
              "profileHTTP": {
                  "bigip": "/Common/http"
              },
              "profileTCP": {
                  "bigip": "/Common/tcp"
              },
              "policyWAF": {
                "use": "/Consul_SD/Ambassador/WAF_Policy"
              },
              "virtualAddresses": [
                "10.3.0.4"
              ],
              "pool": "gateway_pool"
            },
            "gateway_pool": {
              "class": "Pool",
              "monitors": [
                "http"
              ],
              "members": [
                {
                  "servicePort": 8080,
                  "serverAddresses": []
                }
              ]
            }
          }
        }
      }
    }
