#!/bin/bash

cd /root/terraform/services
terraform init

cat << EOF > /root/terraform/services/terraform.tfvars
gcp_project_id="$(echo $INSTRUQT_GCP_PROJECT_CONSUL_PROJECT_ID)"
EOF

set-workdir /root/terraform/services

exit 0
