#!/bin/bash

sleep 10
aws configure set default.region us-east-1
aws ec2 create-default-vpc

aws ec2 import-key-pair --key-name "instruqt" --public-key-material file://~/.ssh/id_rsa.pub
eval `ssh-agent -s`

#install terraform
cd /tmp
echo "installing terraform..."
curl -O https://releases.hashicorp.com/terraform/0.12.23/terraform_0.12.23_linux_amd64.zip
unzip terraform_0.12.23_linux_amd64.zip
mv terraform /usr/local/bin/terraform
rm -f *.zip
cd /root

#get assets
echo "cloning assets..."
git clone -b add-consul-instruqt-ent-aws https://github.com/hashicorp/field-workshops-consul.git
cp -r field-workshops-consul/instruqt-tracks/consul-enterprise-on-aws/terraform .
cp -r field-workshops-consul/instruqt-tracks/consul-enterprise-on-aws/packer .
rm -rf field-workshops-consul

#provision
cd /root/terraform/infra
echo "running terraform..."
/usr/local/bin/terraform init
/usr/local/bin/terraform apply -auto-approve

exit 0
