#!/bin/bash

# Allow instruqt time to do its thing
sleep 10

eval "$(ssh-agent -s)"
ssh-add ~/.ssh/id_rsa

bastion_ip=$(terraform output -state /root/terraform/vnet/terraform.tfstate bastion_ip)
echo "export bastion_ip=${bastion_ip}" >> ~/.bashrc

exit 0
