# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0
name: hashicorp/field-workshops-consul/instruqt-track-test
on:
  workflow_call:
    inputs:
      working_directory:
        required: true
        type: string
    secrets:
      INSTRUQT_TOKEN:
        required: true
env:
  # See IL-559 for information about the source of these # secrets and variables
  INSTRUQT_TOKEN: ${{ secrets.INSTRUQT_TOKEN }}
jobs:
  test-track:
    runs-on: ubuntu-latest
    steps:
    - name: Instruqt Test Loop
      id: instruqt-test
      working-directory: ${{ inputs.working_directory }}
      run: |-
        n=0
        until [ $n -ge 3 ]; do
          echo "Test ${n}"
          instruqt track test --skip-fail-check && break
          n$[$n+1]
          sleep 60
        done
        if [ $n -ge 3 ]; then
          echo "Instruqt track test failed after ${n} attempts"
          exit 1
        fi
