# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0
name: hashicorp/field-workshops-consul/instruqt-track-deploy
on:
  workflow_call:
    inputs:
      INSTRUQT_CLI_URI:
        required: true
        type: string
      working_directory:
        required: true
        type: string
    secrets:
      INSTRUQT_TOKEN:
        required: true
env:
  # See IL-559 for information about the source of these
  # secrets and variables
  INSTRUQT_TOKEN: ${{ secrets.INSTRUQT_TOKEN }}
jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - run: |-
          echo "github:"
          echo '${{ toJSON(github) }}'
          echo "job:"
          echo '${{ toJSON(job) }}'
  test-track:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      id: checkout-source
      uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
    - name: Get Instruqt CLI
      id: get-instruqt-cli
      run: |-
        curl -Lo instruqt.zip "${{ inputs.INSTRUQT_CLI_URI }}"
        unzip instruqt.zip
        mkdir -p "${HOME}/.local/bin/"
        mv instruqt "${HOME}/.local/bin/"
        chmod +x "${HOME}/.local/bin/instruqt"
        echo "${HOME}/.local/bin" >> "${GITHUB_PATH}"
    - name: Instruqt Validate
      id: instruqt-validate
      working-directory: ${{ inputs.working_directory }}
      run: instruqt track validate
    - name: Instruqt Push
      id: instruqt-push
      working-directory: ${{ inputs.working_directory }}
      run: instruqt track push --force
