name: hashicorp/field-workshops-consul/nightly-build
on:
  schedule:
  - cron: 0 1 * * *
#   # 'filters' was not transformed because there is no suitable equivalent in GitHub Actions
env:
  GCLOUD_SERVICE_KEY: xxxxm" }
  GOOGLE_COMPUTE_REGION: xxxxt1-b
  GOOGLE_PROJECT_ID: xxxxcorp
  HC_CONSUL_LICENSE: xxxxHU6Q
  HC_VAULT_LICENSE: xxxxHU6Q
  INSTRUQT_TOKEN: xxxx3d7b
jobs:
  license-cloud-client:
    runs-on: ubuntu-latest
    env:
      PACKER_VERSION: 1.7.0
      TF_VERSION: 0.13.5
      VAULT_VERSION: 1.8.0+ent
      NOMAD_VERSION: 1.0.4+ent
      CONSUL_VERSION: 1.10.2+ent
      CONSUL_TAG: v1.10.2
      ENVOY_VERSION: 1.18.3
    steps:
    # Ensure parameter if_key_exists is set correctly
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2.5.0
      with:
        key: "${{ secrets.CIRCLE_CI_SSH_KEY }}"
        name: circle_ci_id_rsa
        known_hosts: "${{ secrets.CIRCLE_CI_KNOWN_HOSTS }}"
        if_key_exists: fail
    - run: git clone git@github.com:hashicorp/instruqt-packer.git
#     # This item has no matching transformer
#     - circleci_gcp_gcr_gcr_auth:
#     # This item has no matching transformer
#     - circleci_gcp_gcr_build_image:
#     # This item has no matching transformer
#     - circleci_gcp_gcr_push_image:
  consul-basics:
    runs-on: ubuntu-latest
    container:
      image: ubuntu
    steps:
    - uses: actions/checkout@v3.4.0
#     # 'setup_remote_docker' was not transformed because there is no suitable equivalent in GitHub Actions
    - name: Instruqt
      run: |-
        cd instruqt-tracks/consul-basics
        echo "Copying track files..."
        docker create -v /track --name track alpine:3.4 /bin/true
        docker cp . track:/track/
        echo "Running instruqt track validate..."
        docker run -e INSTRUQT_TOKEN=$INSTRUQT_TOKEN --workdir="/track" --volumes-from track instruqt/cli track validate
        echo "Running instruqt track push..."
        docker run -e INSTRUQT_TOKEN=$INSTRUQT_TOKEN --workdir="/track" --volumes-from track instruqt/cli track push --force
        echo "Running instruqt track test..."
        n=0
        until [ $n -ge 3 ]; do
          docker run -e INSTRUQT_TOKEN=$INSTRUQT_TOKEN --workdir="/track" --volumes-from track instruqt/cli track test --skip-fail-check  && break
          n=$[$n+1]
          sleep 60
        done
        if [ $n -ge 3 ]; then
          echo "Instruqt track test failed three times."
          exit 1
        fi
  service-discovery-with-consul:
    runs-on: ubuntu-latest
    container:
      image: ubuntu
    steps:
    - uses: actions/checkout@v3.4.0
#     # 'setup_remote_docker' was not transformed because there is no suitable equivalent in GitHub Actions
    - name: Instruqt
      run: |-
        cd instruqt-tracks/service-discovery-with-consul
        echo "Copying track files..."
        docker create -v /track --name track alpine:3.4 /bin/true
        docker cp . track:/track/
        echo "Running instruqt track validate..."
        docker run -e INSTRUQT_TOKEN=$INSTRUQT_TOKEN --workdir="/track" --volumes-from track instruqt/cli track validate
        echo "Running instruqt track push..."
        docker run -e INSTRUQT_TOKEN=$INSTRUQT_TOKEN --workdir="/track" --volumes-from track instruqt/cli track push --force
        echo "Running instruqt track test..."
        n=0
        until [ $n -ge 3 ]; do
          docker run -e INSTRUQT_TOKEN=$INSTRUQT_TOKEN --workdir="/track" --volumes-from track instruqt/cli track test --skip-fail-check  && break
          n=$[$n+1]
          sleep 60
        done
        if [ $n -ge 3 ]; then
          echo "Instruqt track test failed three times."
          exit 1
        fi
  service-mesh-with-consul:
    runs-on: ubuntu-latest
    container:
      image: ubuntu
    steps:
    - uses: actions/checkout@v3.4.0
#     # 'setup_remote_docker' was not transformed because there is no suitable equivalent in GitHub Actions
    - name: Instruqt
      run: |-
        cd instruqt-tracks/service-mesh-with-consul
        echo "Copying track files..."
        docker create -v /track --name track alpine:3.4 /bin/true
        docker cp . track:/track/
        echo "Running instruqt track validate..."
        docker run -e INSTRUQT_TOKEN=$INSTRUQT_TOKEN --workdir="/track" --volumes-from track instruqt/cli track validate
        echo "Running instruqt track push..."
        docker run -e INSTRUQT_TOKEN=$INSTRUQT_TOKEN --workdir="/track" --volumes-from track instruqt/cli track push --force
        echo "Running instruqt track test..."
        n=0
        until [ $n -ge 3 ]; do
          docker run -e INSTRUQT_TOKEN=$INSTRUQT_TOKEN --workdir="/track" --volumes-from track instruqt/cli track test --skip-fail-check  && break
          n=$[$n+1]
          sleep 60
        done
        if [ $n -ge 3 ]; then
          echo "Instruqt track test failed three times."
          exit 1
        fi
  network-infrastructure-automation:
    runs-on: ubuntu-latest
    container:
      image: ubuntu
    steps:
    - uses: actions/checkout@v3.4.0
#     # 'setup_remote_docker' was not transformed because there is no suitable equivalent in GitHub Actions
    - name: Instruqt
      run: |-
        cd instruqt-tracks/network-infrastructure-automation
        echo "Copying track files..."
        docker create -v /track --name track alpine:3.4 /bin/true
        docker cp . track:/track/
        echo "Running instruqt track validate..."
        docker run -e INSTRUQT_TOKEN=$INSTRUQT_TOKEN --workdir="/track" --volumes-from track instruqt/cli track validate
        echo "Running instruqt track push..."
        docker run -e INSTRUQT_TOKEN=$INSTRUQT_TOKEN --workdir="/track" --volumes-from track instruqt/cli track push --force
        echo "Running instruqt track test..."
        n=0
        until [ $n -ge 3 ]; do
          docker run -e INSTRUQT_TOKEN=$INSTRUQT_TOKEN --workdir="/track" --volumes-from track instruqt/cli track test --skip-fail-check  && break
          n=$[$n+1]
          sleep 60
        done
        if [ $n -ge 3 ]; then
          echo "Instruqt track test failed three times."
          exit 1
        fi
  life-of-a-developer:
    runs-on: ubuntu-latest
    container:
      image: ubuntu
    steps:
    - uses: actions/checkout@v3.4.0
#     # 'setup_remote_docker' was not transformed because there is no suitable equivalent in GitHub Actions
    - name: Instruqt
      run: |-
        cd instruqt-tracks/consul-life-of-a-developer
        echo "Copying track files..."
        docker create -v /track --name track alpine:3.4 /bin/true
        docker cp . track:/track/
        echo "Running instruqt track validate..."
        docker run -e INSTRUQT_TOKEN=$INSTRUQT_TOKEN --workdir="/track" --volumes-from track instruqt/cli track validate
        echo "Running instruqt track push..."
        docker run -e INSTRUQT_TOKEN=$INSTRUQT_TOKEN --workdir="/track" --volumes-from track instruqt/cli track push --force
        echo "Running instruqt track test..."
        n=0
        until [ $n -ge 3 ]; do
          docker run -e INSTRUQT_TOKEN=$INSTRUQT_TOKEN --workdir="/track" --volumes-from track instruqt/cli track test --skip-fail-check  && break
          n=$[$n+1]
          sleep 60
        done
        if [ $n -ge 3 ]; then
          echo "Instruqt track test failed three times."
          exit 1
        fi
  multi-cloud-consul:
    runs-on: ubuntu-latest
    container:
      image: ubuntu
    needs:
    - license-cloud-client
    steps:
    - uses: actions/checkout@v3.4.0
#     # 'setup_remote_docker' was not transformed because there is no suitable equivalent in GitHub Actions
    - name: Instruqt
      run: |-
        cd instruqt-tracks/multi-cloud-service-networking-with-consul
        echo "Copying track files..."
        docker create -v /track --name track alpine:3.4 /bin/true
        docker cp . track:/track/
        echo "Running instruqt track validate..."
        docker run -e INSTRUQT_TOKEN=$INSTRUQT_TOKEN --workdir="/track" --volumes-from track instruqt/cli track validate
        echo "Running instruqt track push..."
        docker run -e INSTRUQT_TOKEN=$INSTRUQT_TOKEN --workdir="/track" --volumes-from track instruqt/cli track push --force
        echo "Running instruqt track test..."
        n=0
        until [ $n -ge 3 ]; do
          docker run -e INSTRUQT_TOKEN=$INSTRUQT_TOKEN --workdir="/track" --volumes-from track instruqt/cli track test --skip-fail-check  && break
          n=$[$n+1]
          sleep 60
        done
        if [ $n -ge 3 ]; then
          echo "Instruqt track test failed three times."
          exit 1
        fi
