# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0
name: hashicorp/field-workshops-consul/nightly-build
on: workflow_dispatch
##   schedule:
##   - cron: 37 1 * * *
env:
  # See IL-559 for information about the source of these
  # secrets and variables
  GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
  GOOGLE_COMPUTE_REGION: ${{ vars.GOOGLE_COMPUTE_REGION }}
  GOOGLE_PROJECT_ID: ${{ vars.GOOGLE_PROJECT_ID }}
  HC_CONSUL_LICENSE: ${{ secrets.HC_CONSUL_LICENSE }}
  HC_VAULT_LICENSE: ${{ secrets.HC_VAULT_LICENSE }}
  INSTRUQT_TOKEN: ${{ secrets.INSTRUQT_TOKEN }}
jobs:
  license-cloud-client:
    runs-on: ubuntu-latest
    ### XXX REMOVE
    if: false
    env:
      # See IL-559 for information about the setting of these
      # variables
      PACKER_VERSION: ${{ vars.PACKER_VERSION }}
      TF_VERSION: ${{ vars.TF_VERSION }}
      VAULT_VERSION: ${{ vars.VAULT_VERSION }}
      NOMAD_VERSION: ${{ vars.NOMAD_VERSION }}
      CONSUL_VERSION: ${{ vars.CONSUL_VERSION }}
      CONSUL_TAG: ${{ vars.CONSUL_TAG }}
      ENVOY_VERSION: ${{ vars.ENVOY_VERSION }}
    steps:
    - name: Checkout Source
      id: checkout-source
      uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      with:
        repository: hashicorp/instruqt-packer
        token: ${{ secrets.HC_GITHUB_SOLUTIONS_ENGINEERING_PAT }}
        path: instruqt-packer
    - name: Write GCloud Key
      id: write-gcloud-key
      run: echo "${GCLOUD_SERVICE_KEY}" > "${HOME}"/gcloud.json
    - name: Auth to GCP
      id: auth-to-gcp
      run: gcloud auth activate-service-account --key-file="${HOME}/gcloud.json" --project "${GOOGLE_PROJECT_ID}"
    - name: Configure Docker
      id: configure-docker
      run: |-
        gcloud auth configure-docker
        gcloud config set project ${GOOGLE_PROJECT_ID}
    - name: Build container
      id: build-container
      run: docker build --build-arg HC_VAULT_LICENSE=${HC_VAULT_LICENSE} --build-arg HC_CONSUL_LICENSE=${HC_CONSUL_LICENSE} --build-arg PACKER_VERSION=${PACKER_VERSION} --build-arg TF_VERSION=${TF_VERSION} --build-arg VAULT_VERSION=${VAULT_VERSION} --build-arg NOMAD_VERSION=${NOMAD_VERSION} --build-arg CONSUL_VERSION=${CONSUL_VERSION} --build-arg ENVOY_VERSION=${ENVOY_VERSION} -f instruqt-packer/consul-cloud-client/Dockerfile -t gcr.io/${GOOGLE_PROJECT_ID}/consul-cloud-client:${CONSUL_TAG} instruqt-packer/consul-cloud-client
    - name: Push container
      id: push-container
      run: docker push gcr.io/${GOOGLE_PROJECT_ID}/consul-cloud-client:${CONSUL_TAG}
  consul-basics:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      id: checkout-source
      uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      with:
        path: field-workshops-consul
    - name: Get Instruqt CLI
      id: get-instruqt-cli
      run: |-
        curl -LO https://github.com/instruqt/cli/releases/download/2074-4823fd3/instruqt-linux-2074-4823fd3.zip
        unzip instruqt-linux-2074-4823fd3.zip
        mkdir -p ${HOME}/.local/bin/
        mv instruqt ${HOME}/.local/bin/
        chmod +x ${HOME}/.local/bin/instruqt
        echo "${HOME}/.local/bin" >> ${GITHUB_PATH}
    - name: Instruqt Validate
      id: instruqt-validate
      working-directory: field-workshops-consul/instruqt-tracks/consul-basic
      run: instruqt track validate
    - name: Instruqt Push
      id: instruqt-push
      working-directory: field-workshops-consul/instruqt-tracks/consul-basic
      run: instruqt track push --force
    - name: Instruqt Test Loop
      id: instruqt-test
      working-directory: field-workshops-consul/instruqt-tracks/consul-basic
      run: |-
        n=0
        until [ $n -ge 3 ]; do
          echo "Test ${n}"
          instruqt track test --skip-fail-check && break
          n$[$n+1]
          sleep 60
        done
        if [ $n -ge 3 ]; then
          echo "Instruqt track test failed after ${n} attempts"
          exit 1
        fi
