# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0
name: hashicorp/field-workshops-consul/nightly-test
on:
  workflow_dispatch:
  schedule:
  # This is UTC
  - cron: 37 4 * * *
permissions:
  contents: read
env:
  # See IL-559 for information about the source of these
  # secrets and variables
  GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
  GOOGLE_COMPUTE_REGION: ${{ vars.GOOGLE_COMPUTE_REGION }}
  GOOGLE_PROJECT_ID: ${{ vars.GOOGLE_PROJECT_ID }}
  HC_CONSUL_LICENSE: ${{ secrets.HC_CONSUL_LICENSE }}
  HC_VAULT_LICENSE: ${{ secrets.HC_VAULT_LICENSE }}
  INSTRUQT_TOKEN: ${{ secrets.INSTRUQT_TOKEN }}
jobs:
  # This should be changed long term: we build a new container
  # every night even though the majority of the time nothing changes.
  # Figure out a way to trigger only when the source changes, or
  # the configuration changes
  license-cloud-client:
    runs-on: ubuntu-latest
    if: false     # XXX remove
    permissions: {}
    env:
      # See IL-559 for information about the setting of these
      # variables
      PACKER_VERSION: ${{ vars.PACKER_VERSION }}
      TF_VERSION: ${{ vars.TF_VERSION }}
      VAULT_VERSION: ${{ vars.VAULT_VERSION }}
      NOMAD_VERSION: ${{ vars.NOMAD_VERSION }}
      CONSUL_VERSION: ${{ vars.CONSUL_VERSION }}
      CONSUL_TAG: ${{ vars.CONSUL_TAG }}
      ENVOY_VERSION: ${{ vars.ENVOY_VERSION }}
    steps:
    - name: Checkout Source
      id: checkout-source
      uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      with:
        repository: hashicorp/instruqt-packer
        token: ${{ secrets.HC_GITHUB_SOLUTIONS_ENGINEERING_PAT }}
        path: instruqt-packer
    - name: Write GCloud Key
      id: write-gcloud-key
      run: echo "${GCLOUD_SERVICE_KEY}" > "${HOME}"/gcloud.json
    - name: Auth to GCP
      id: auth-to-gcp
      run: gcloud auth activate-service-account --key-file="${HOME}/gcloud.json" --project "${GOOGLE_PROJECT_ID}"
    - name: Configure Docker
      id: configure-docker
      run: |-
        gcloud auth configure-docker
        gcloud config set project ${GOOGLE_PROJECT_ID}
    - name: Build container
      id: build-container
      run: docker build --build-arg HC_VAULT_LICENSE=${HC_VAULT_LICENSE} --build-arg HC_CONSUL_LICENSE=${HC_CONSUL_LICENSE} --build-arg PACKER_VERSION=${PACKER_VERSION} --build-arg TF_VERSION=${TF_VERSION} --build-arg VAULT_VERSION=${VAULT_VERSION} --build-arg NOMAD_VERSION=${NOMAD_VERSION} --build-arg CONSUL_VERSION=${CONSUL_VERSION} --build-arg ENVOY_VERSION=${ENVOY_VERSION} -f instruqt-packer/consul-cloud-client/Dockerfile -t gcr.io/${GOOGLE_PROJECT_ID}/consul-cloud-client:${CONSUL_TAG} instruqt-packer/consul-cloud-client
    - name: Push container
      id: push-container
      run: docker push gcr.io/${GOOGLE_PROJECT_ID}/consul-cloud-client:${CONSUL_TAG}
  consul-basics:
    uses: ./.github/workflows/instruqt-track-test.yml
    with:
      working_directory: "instruqt-tracks/consul-basics"
      INSTRUQT_CLI_URI: ${{ vars.INSTRUQT_CLI_URI }}
    secrets:
      INSTRUQT_TOKEN: ${{ secrets.INSTRUQT_TOKEN }}
  service-discovery-with-consul:
    uses: ./.github/workflows/instruqt-track-test.yml
    if: false     # XXX remove
    with:
      working_directory: "instruqt-tracks/service-discovery-with-consul"
      INSTRUQT_CLI_URI: ${{ vars.INSTRUQT_CLI_URI }}
    secrets:
      INSTRUQT_TOKEN: ${{ secrets.INSTRUQT_TOKEN }}
  service-mesh-with-consul:
    uses: ./.github/workflows/instruqt-track-test.yml
    if: false     # XXX remove
    with:
      working_directory: "instruqt-tracks/service-mesh-with-consul"
      INSTRUQT_CLI_URI: ${{ vars.INSTRUQT_CLI_URI }}
    secrets:
      INSTRUQT_TOKEN: ${{ secrets.INSTRUQT_TOKEN }}
  multi-cloud-consul:
    uses: ./.github/workflows/instruqt-track-test.yml
    if: false     # XXX remove
    needs: license-cloud-client
    with:
      working_directory: "instruqt-tracks/multi-cloud-service-networking-with-consul"
      INSTRUQT_CLI_URI: ${{ vars.INSTRUQT_CLI_URI }}
    secrets:
      INSTRUQT_TOKEN: ${{ secrets.INSTRUQT_TOKEN }}
  network-infrastructure-automation:
    uses: ./.github/workflows/instruqt-track-test.yml
    if: false     # XXX remove
    with:
      working_directory: "instruqt-tracks/network-infrastructure-automation"
      INSTRUQT_CLI_URI: ${{ vars.INSTRUQT_CLI_URI }}
    secrets:
      INSTRUQT_TOKEN: ${{ secrets.INSTRUQT_TOKEN }}
  life-of-a-developer:
    uses: ./.github/workflows/instruqt-track-test.yml
    if: false     # XXX remove
    with:
      working_directory: "instruqt-tracks/consul-life-of-a-developer"
      INSTRUQT_CLI_URI: ${{ vars.INSTRUQT_CLI_URI }}
    secrets:
      INSTRUQT_TOKEN: ${{ secrets.INSTRUQT_TOKEN }}
